/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: True
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): dafa576fa8f9dd5aa33eb8d4b635033f8158183b77f9cd20b689f9e6dcc8bb19
 * Model name: model
 * Graph name: test_reduce_sum_empty_set
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

static inline float ref_scalar_f32_abs(float a) {
    return fabsf(a);
}

static inline float ref_scalar_f32_exp(float a) {
    return expf(a);
}

static inline float ref_scalar_f32_log(float a) {
    return logf(a);
}

static inline float ref_scalar_f32_sqrt(float a) {
    return sqrtf(a);
}

/*
 * Node 0:
 * OpType: ReduceSum
 * Name: n/a
 * Inputs: data, axes
 * Outputs: reduced
 * Attrs:
 *   keepdims: 1
 */
EMX_NODE_FN void node0_reducesum(const float input0[2][1][4], float output[2][1][4]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                float acc = 0.0f;
                for (idx_t r0 = 0; r0 < 0; ++r0) {
                    acc += input0[i0][r0][i2];
                }
                output[i0][i1][i2] = acc;
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float data[restrict 2][1][4], const int64_t axes[restrict 1], float reduced[restrict 2][1][4]) {
    node0_reducesum(data, reduced);
}





static const float data_testbench_data[] = {
    {
        {
            0.0f, 0.0f, 0.0f, 0.0f
        }
    },
    {
        {
            0.0f, 0.0f, 0.0f, 0.0f
        }
    }
};
static const int64_t axes_testbench_data[] = {
    1LL
};

__attribute__((weak, noinline)) void timer_start(void) {}
__attribute__((weak, noinline)) void timer_stop(void) {}


static void testbench_init_constant_input(float data[2][1][4], int64_t axes[1]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 0; ++i1) {
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                data[i0][i1][i2] = data_testbench_data[((i0 * 1 + i1) * 4 + i2)];
            }
        }
    }
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        axes[i0] = axes_testbench_data[i0];
    }
}

static int testbench_read_input_file(
const char *input_path) {
    (void)input_path;
    return 0;
}

static void testbench_fill_random_input(void) {
    (void)0;
}

static void testbench_print_json(
float reduced[2][1][4]) {
    printf("{\n  \"outputs\": {\n");
    printf("    \"reduced\": {\"shape\": [2,1,4], \"data\":\n      ");
    printf("[");
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("\"%a\"", (double)reduced[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");
    printf("\n  }\n}\n");
}

static int testbench_run(const char *input_path) {

    float data[2][1][4];
    int64_t axes[1];

    testbench_init_constant_input(data, axes);
    if (input_path) {
        if (testbench_read_input_file(input_path) != 0) {
            return 1;
        }
    } else {
        testbench_fill_random_input();
    }

    float reduced[2][1][4];

    if (!model_load("model.bin")) {
        return 1;
    }

    timer_start();
    model(data, axes, reduced);
    timer_stop();

    testbench_print_json(reduced);
    return 0;
}

int main(int argc, char **argv) {
    const char *input_path = NULL;

    if (argc > 1) {
        input_path = argv[1];
    }

    return testbench_run(input_path);
}
