/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: verify onnx-org/onnx/backend/test/data/node/test_layer_normalization_3d_axis_negative_3_epsilon/model.onnx --test-data-dir onnx-org/onnx/backend/test/data/node/test_layer_normalization_3d_axis_negative_3_epsilon/test_data_set_0 --keep-temp-dir --temp-dir tmp
 * Model checksum (sha256): 12c69e232bbb1d7c6fbd62816c4e0cb5508056d65273c74b9fec442ffaf55844
 * Model name: model
 * Graph name: test_layer_normalization_3d_axis_negative_3_epsilon
 * Inputs: 3 Outputs: 3 Nodes: 1 Initializers: 0
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=17
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Node 0:
 * OpType: LayerNormalization
 * Name: n/a
 * Inputs: X, W, B
 * Outputs: Y, Mean, InvStdDev
 * Attrs:
 *   axis: -3
 *   epsilon: 0.10000000149011612
 */
static inline void node0_layernormalization(const float input0[2][3][5], const float scale[2][3][5], const float bias[2][3][5], float output[2][3][5], float mean_output[1][1][1], float invstd_output[1][1][1]) {
    float sum = 0.0f;
    float sum_comp = 0.0f;
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                float kahan_value = (float)input0[i0][i1][i2];
                float kahan_y = kahan_value - sum_comp;
                float kahan_t = sum + kahan_y;
                sum_comp = (kahan_t - sum) - kahan_y;
                sum = kahan_t;
            }
        }
    }
    float mean = sum / 30;
    float var = 0.0f;
    float var_comp = 0.0f;
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                float diff = (float)input0[i0][i1][i2] - mean;
                float kahan_value = diff * diff;
                float kahan_y = kahan_value - var_comp;
                float kahan_t = var + kahan_y;
                var_comp = (kahan_t - var) - kahan_y;
                var = kahan_t;
            }
        }
    }
    var = var / 30;
    float inv_std = 1.0f / sqrtf(var + 0.100000001f);
    mean_output[0][0][0] = mean;
    invstd_output[0][0][0] = inv_std;
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                float value = ((float)input0[i0][i1][i2] - mean) * inv_std;
                value = value * scale[i0][i1][i2] + bias[i0][i1][i2];
                output[i0][i1][i2] = value;
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float X[restrict 2][3][5], const float W[restrict 2][3][5], const float B[restrict 2][3][5], float Y[restrict 2][3][5], float Mean[restrict 1][1][1], float InvStdDev[restrict 1][1][1]) {
    node0_layernormalization(X, W, B, Y, Mean, InvStdDev);
}





static const float X_testbench_data[] = {
    1.76405239f,    0.400157213f,    0.97873801f,    2.24089313f,    1.867558f,    -0.977277875f,    0.950088441f,    -0.151357204f,    -0.103218853f,    0.410598516f,    0.144043565f,    1.45427346f,    0.761037707f,    0.121675014f,    0.443863243f,    0.333674341f,    1.49407911f,    -0.205158263f,    0.313067704f,    -0.854095757f,    -2.55298972f,    0.653618574f,    0.864436209f,    -0.742165029f,    2.26975465f,    -1.45436573f,    0.0457585156f,    -0.187183857f,    1.53277922f,    1.4693588f};
static const float W_testbench_data[] = {
    -0.403176934f,    1.22244501f,    0.208274975f,    0.976639032f,    0.356366396f,    0.706573188f,    0.0105000203f,    1.78587055f,    0.126912087f,    0.401989371f,    1.8831507f,    -1.34775901f,    -1.27048504f,    0.96939671f,    -1.17312336f,    1.94362116f,    -0.413618982f,    -0.747454822f,    1.92294204f,    1.48051476f,    1.86755896f,    0.906044662f,    -0.861225665f,    1.91006494f,    -0.268003374f,    0.802456379f,    0.947251976f,    -0.155010089f,    0.614079356f,    0.9222067f};
static const float B_testbench_data[] = {
    0.376425534f,    -1.09940076f,    0.298238188f,    1.32638586f,    -0.694567859f,    -0.14963454f,    -0.435153544f,    1.84926379f,    0.672294736f,    0.407461822f,    -0.769916058f,    0.539249182f,    -0.674332678f,    0.0318305567f,    -0.635846078f,    0.676433265f,    0.576590836f,    -0.208298758f,    0.396006703f,    -1.09306157f,    -1.49125755f,    0.439391702f,    0.166673496f,    0.635031462f,    2.38314486f,    0.944479465f,    -0.912822247f,    1.11701632f,    -1.31590736f,    -0.461584598f};

int main(void) {

    float X[2][3][5];
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                X[i0][i1][i2] = X_testbench_data[((i0 * 3 + i1) * 5 + i2)];
            }
        }
    }
    float W[2][3][5];
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                W[i0][i1][i2] = W_testbench_data[((i0 * 3 + i1) * 5 + i2)];
            }
        }
    }
    float B[2][3][5];
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                B[i0][i1][i2] = B_testbench_data[((i0 * 3 + i1) * 5 + i2)];
            }
        }
    }

    float Y[2][3][5];
    float Mean[1][1][1];
    float InvStdDev[1][1][1];

    if (!model_load("model.bin")) {
        return 1;
    }
    model(X, W, B, Y, Mean, InvStdDev);

    printf("{\"inputs\":{");
    printf("\"X\":{\"shape\":[2,3,5],\"data\":");
    printf("[");
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        if (i0) {
            printf(",");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("\"%a\"", (double)X[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");
    printf(",");
    printf("\"W\":{\"shape\":[2,3,5],\"data\":");
    printf("[");
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        if (i0) {
            printf(",");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("\"%a\"", (double)W[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");
    printf(",");
    printf("\"B\":{\"shape\":[2,3,5],\"data\":");
    printf("[");
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        if (i0) {
            printf(",");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("\"%a\"", (double)B[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");

    printf("},\"outputs\":{");
    printf("\"Y\":{\"shape\":[2,3,5],\"data\":");
    printf("[");
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        if (i0) {
            printf(",");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 5; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("\"%a\"", (double)Y[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");
    printf(",");
    printf("\"Mean\":{\"shape\":[1,1,1],\"data\":");
    printf("[");
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        if (i0) {
            printf(",");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 1; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("\"%a\"", (double)Mean[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");
    printf(",");
    printf("\"InvStdDev\":{\"shape\":[1,1,1],\"data\":");
    printf("[");
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        if (i0) {
            printf(",");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 1; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("\"%a\"", (double)InvStdDev[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");
    printf("}}\n");
    return 0;
}
