/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: compile infineon_lstm_small.onnx --emit-testbench
 * Model checksum (sha256): b4435216ca027ed4292ef6a195f86c666bbd8dbc9174167f6e8364dfed57490e
 * Model name: model
 * Graph name: torch_jit
 * Inputs: 1 Outputs: 1 Nodes: 4 Initializers: 7
 * IR version: 6
 * Model version: n/a
 * Domain: n/a
 * Producer: pytorch (version: 1.13.1)
 * Opset imports: ai.onnx=11
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Weight 1:
 * Name: weight1_onnx__lstm_107
 * Shape: (1, 64, 3)
 * Elements: 192
 * Dtype: float
 */
static const float weight1_onnx__lstm_107[1][64][3] = {
    {
        {
            -0x1.641cccp-3f, -0x1.a1e0ecp-3f, -0x1.8156a8p-3f
        },
        {
            -0x1.ca5c90p-5f, 0x1.039618p-3f, 0x1.89256cp-3f
        },
        {
            -0x1.dd0e30p-5f, -0x1.911120p-4f, -0x1.a08034p-3f
        },
        {
            0x1.6bd200p-10f, -0x1.893994p-3f, 0x1.00d570p-5f
        },
        {
            -0x1.4e7700p-7f, 0x1.488f00p-4f, 0x1.985558p-3f
        },
        {
            -0x1.747000p-6f, -0x1.401a10p-3f, 0x1.892b00p-6f
        },
        {
            -0x1.e45848p-3f, -0x1.1dbb90p-4f, 0x1.423e40p-7f
        },
        {
            -0x1.3f9c80p-6f, 0x1.86aa7cp-3f, -0x1.12a010p-5f
        },
        {
            0x1.3fc054p-3f, 0x1.860f30p-3f, 0x1.ca7ac4p-3f
        },
        {
            0x1.d08b70p-5f, -0x1.befb0cp-3f, 0x1.64b590p-5f
        },
        {
            0x1.983c48p-4f, -0x1.9bdcacp-3f, 0x1.0e6668p-3f
        },
        {
            0x1.bdb340p-5f, 0x1.c6d4b8p-3f, -0x1.5dec84p-3f
        },
        {
            -0x1.873c10p-5f, 0x1.ca26e8p-3f, 0x1.c1e078p-4f
        },
        {
            -0x1.178bb4p-3f, -0x1.007100p-8f, 0x1.a60760p-5f
        },
        {
            -0x1.9db37cp-3f, 0x1.384788p-3f, -0x1.84389cp-3f
        },
        {
            0x1.b50308p-4f, -0x1.a69db4p-3f, 0x1.47f5f0p-4f
        },
        {
            0x1.10c91cp-3f, 0x1.412fe8p-4f, 0x1.8b9960p-6f
        },
        {
            -0x1.58974cp-3f, -0x1.326810p-5f, -0x1.269280p-6f
        },
        {
            -0x1.69ccacp-3f, 0x1.0b5f00p-7f, -0x1.4dfa80p-4f
        },
        {
            -0x1.cb0eb4p-3f, 0x1.68b11cp-3f, -0x1.829fc0p-6f
        },
        {
            0x1.3114b8p-3f, 0x1.9019d8p-3f, -0x1.e97368p-3f
        },
        {
            0x1.f9a460p-4f, -0x1.495070p-4f, -0x1.a87960p-3f
        },
        {
            0x1.7d9e5cp-3f, -0x1.ea7554p-3f, -0x1.e534c8p-3f
        },
        {
            0x1.36cd20p-5f, 0x1.417908p-4f, 0x1.8deee0p-6f
        },
        {
            -0x1.4ee2b8p-3f, 0x1.c79454p-3f, -0x1.086b40p-4f
        },
        {
            0x1.1dcc94p-3f, 0x1.fd48e8p-3f, 0x1.052040p-6f
        },
        {
            -0x1.9e962cp-3f, -0x1.ba2e80p-8f, -0x1.edb500p-4f
        },
        {
            -0x1.03b460p-3f, -0x1.d73f04p-3f, -0x1.c7125cp-3f
        },
        {
            0x1.45efd4p-3f, 0x1.8fdc88p-3f, 0x1.a33d60p-3f
        },
        {
            -0x1.29d100p-3f, 0x1.c664dcp-3f, 0x1.9e4628p-4f
        },
        {
            0x1.99b328p-4f, -0x1.1dd5a0p-6f, 0x1.3d3344p-3f
        },
        {
            0x1.69cb64p-3f, -0x1.0971f4p-3f, -0x1.38b7c0p-3f
        },
        {
            0x1.173e80p-5f, -0x1.08301cp-3f, -0x1.22bf54p-3f
        },
        {
            0x1.2bd008p-4f, 0x1.247990p-5f, -0x1.0888a0p-6f
        },
        {
            -0x1.31d360p-6f, 0x1.dfe268p-3f, -0x1.04d19cp-3f
        },
        {
            0x1.0e3140p-7f, -0x1.791660p-6f, -0x1.be0980p-4f
        },
        {
            -0x1.87d530p-4f, -0x1.42a2d0p-5f, 0x1.c22f90p-5f
        },
        {
            -0x1.4722c0p-7f, 0x1.7ecf80p-6f, -0x1.d9f05cp-3f
        },
        {
            -0x1.8351a0p-3f, 0x1.4c57c8p-3f, -0x1.505c00p-8f
        },
        {
            -0x1.c4bdb0p-3f, 0x1.d50c98p-4f, -0x1.872d60p-5f
        },
        {
            -0x1.1d01e8p-4f, 0x1.dcf934p-3f, 0x1.e07800p-9f
        },
        {
            -0x1.1118f0p-4f, 0x1.e6afa0p-5f, -0x1.6b8a00p-8f
        },
        {
            -0x1.019070p-4f, 0x1.a5ba74p-3f, 0x1.4e856cp-3f
        },
        {
            -0x1.08a824p-3f, -0x1.110f7cp-3f, 0x1.2bd8e4p-3f
        },
        {
            -0x1.24de38p-4f, 0x1.800494p-3f, -0x1.177e1cp-3f
        },
        {
            -0x1.19d0c0p-4f, 0x1.6590f8p-3f, -0x1.de6300p-7f
        },
        {
            -0x1.a66e20p-6f, -0x1.610a74p-3f, -0x1.6488d8p-3f
        },
        {
            0x1.b6bbb0p-5f, 0x1.b7a1c0p-4f, 0x1.ec2a78p-4f
        },
        {
            -0x1.3a055cp-3f, -0x1.f77a70p-3f, -0x1.d298b0p-5f
        },
        {
            -0x1.47d070p-3f, -0x1.972478p-4f, 0x1.dd5fe0p-3f
        },
        {
            -0x1.02b658p-4f, -0x1.9bc328p-4f, -0x1.0621c0p-3f
        },
        {
            -0x1.9c057cp-3f, -0x1.9991c0p-5f, 0x1.d738a0p-6f
        },
        {
            -0x1.0ba8e0p-3f, 0x1.032d78p-4f, -0x1.7ebeb0p-3f
        },
        {
            -0x1.8cea80p-6f, 0x1.675ac0p-3f, 0x1.943fd8p-4f
        },
        {
            -0x1.2d0e2cp-3f, 0x1.cf4884p-3f, -0x1.fa6b18p-3f
        },
        {
            0x1.eca3acp-3f, 0x1.0bd208p-3f, -0x1.8c25c0p-5f
        },
        {
            0x1.58e948p-3f, 0x1.4dec80p-6f, 0x1.d5b27cp-3f
        },
        {
            0x1.8e9648p-3f, 0x1.f9b040p-4f, -0x1.f724c0p-5f
        },
        {
            0x1.e3493cp-3f, -0x1.bd8bb8p-3f, -0x1.b537bcp-3f
        },
        {
            -0x1.43c0c0p-6f, 0x1.f67fa4p-3f, 0x1.51a50cp-3f
        },
        {
            0x1.ca33a0p-3f, 0x1.3ddafcp-3f, 0x1.2d07b8p-3f
        },
        {
            -0x1.d4e3e0p-6f, 0x1.99ac98p-3f, 0x1.f0d120p-4f
        },
        {
            0x1.f7ea40p-5f, -0x1.1f9634p-3f, 0x1.47c4c0p-4f
        },
        {
            0x1.abcd90p-4f, 0x1.c57850p-3f, -0x1.c785c0p-3f
        }
    }
};

/*
 * Weight 2:
 * Name: weight2_onnx__lstm_108
 * Shape: (1, 64, 16)
 * Elements: 1024
 * Dtype: float
 */
static const float weight2_onnx__lstm_108[1][64][16] = {
    {
        {
            0x1.558e18p-4f, -0x1.7d67e0p-6f, -0x1.88a668p-3f, -0x1.8d64a8p-4f, -0x1.9834f0p-5f, 0x1.6012e8p-4f, 0x1.075b64p-3f, 0x1.bbf8bcp-3f,
            0x1.248870p-4f, -0x1.474c6cp-3f, -0x1.ee1800p-6f, -0x1.ac62e0p-5f, -0x1.dbe260p-5f, 0x1.bab730p-3f, 0x1.fe40a4p-3f, -0x1.0286b8p-3f
        },
        {
            0x1.776200p-7f, 0x1.5f14e8p-4f, 0x1.23fde8p-3f, -0x1.d564a8p-4f, 0x1.a50b80p-4f, -0x1.eae8d0p-3f, 0x1.530000p-16f, 0x1.4aaf88p-3f,
            -0x1.669a70p-3f, 0x1.71b8f8p-4f, -0x1.915a14p-3f, 0x1.5e71b8p-3f, -0x1.615d38p-3f, -0x1.824d64p-3f, 0x1.b3ff70p-3f, 0x1.c31180p-3f
        },
        {
            -0x1.64f948p-4f, 0x1.14831cp-3f, 0x1.6a6864p-3f, -0x1.f644d0p-3f, 0x1.5a8cc0p-4f, 0x1.f78a30p-3f, 0x1.b71948p-3f, 0x1.2a29c0p-4f,
            -0x1.614040p-5f, 0x1.751f70p-4f, -0x1.7455f8p-4f, 0x1.5d75e8p-3f, -0x1.488fd4p-3f, -0x1.4e25b0p-4f, 0x1.6f2234p-3f, -0x1.2f2844p-3f
        },
        {
            -0x1.717250p-3f, 0x1.9e9538p-3f, 0x1.cacb80p-4f, 0x1.8d9eccp-3f, 0x1.f2da38p-4f, 0x1.a52440p-7f, -0x1.aea000p-6f, 0x1.2e97f0p-4f,
            -0x1.e54c2cp-3f, 0x1.364770p-5f, 0x1.e93400p-11f, -0x1.32556cp-3f, -0x1.c1a620p-4f, 0x1.ae30e0p-5f, -0x1.6a16b4p-3f, -0x1.51866cp-3f
        },
        {
            0x1.4b0200p-5f, -0x1.924300p-6f, 0x1.ce8e50p-3f, -0x1.92c834p-3f, -0x1.476420p-4f, -0x1.16e344p-3f, -0x1.ae8830p-3f, -0x1.a12e4cp-3f,
            0x1.682570p-3f, 0x1.326b80p-7f, 0x1.897820p-3f, 0x1.e25998p-3f, 0x1.a19d40p-6f, 0x1.d51370p-4f, 0x1.78e3a0p-5f, 0x1.9f22c8p-3f
        },
        {
            0x1.fb83a4p-3f, 0x1.d091d8p-4f, 0x1.b16100p-4f, -0x1.e18848p-3f, -0x1.c54190p-5f, -0x1.07d2c0p-6f, 0x1.738b80p-8f, 0x1.fd5c18p-3f,
            -0x1.e77ce8p-4f, -0x1.78b330p-5f, -0x1.9fb4acp-3f, -0x1.166f98p-4f, -0x1.3674e8p-4f, 0x1.f66008p-3f, -0x1.ae55b8p-4f, 0x1.0b6b00p-9f
        },
        {
            -0x1.2dc3d8p-3f, -0x1.53e6b8p-4f, 0x1.9cb240p-6f, -0x1.93a740p-6f, 0x1.526e68p-3f, -0x1.dff048p-3f, 0x1.8e2c30p-5f, 0x1.4b23e4p-3f,
            0x1.7d19d8p-3f, -0x1.37bf48p-4f, -0x1.d9c1d0p-5f, -0x1.118f0cp-3f, -0x1.1efcacp-3f, -0x1.c532ccp-3f, 0x1.df16f8p-3f, 0x1.a14d60p-6f
        },
        {
            0x1.497d90p-5f, 0x1.524cf0p-4f, 0x1.0a5bd8p-4f, -0x1.636f68p-4f, -0x1.ab5738p-3f, -0x1.cb6ae0p-6f, -0x1.f76f78p-4f, 0x1.00a258p-3f,
            -0x1.1ba7a4p-3f, -0x1.93a030p-3f, -0x1.bc0d60p-5f, -0x1.b39ae0p-5f, -0x1.06b250p-4f, -0x1.cc1768p-3f, 0x1.405644p-3f, -0x1.5ff03cp-3f
        },
        {
            -0x1.3e10c0p-3f, 0x1.d18e40p-5f, 0x1.d5abe0p-4f, 0x1.6bce70p-3f, -0x1.1ed17cp-3f, 0x1.682e48p-4f, 0x1.a05ce0p-4f, -0x1.002abcp-3f,
            -0x1.374c30p-5f, -0x1.080650p-5f, 0x1.2b2c20p-5f, -0x1.045500p-7f, 0x1.233470p-3f, 0x1.21b9e4p-3f, -0x1.76ab08p-3f, 0x1.fe756cp-3f
        },
        {
            0x1.2a8984p-3f, 0x1.782e00p-4f, 0x1.1fd5d4p-3f, 0x1.2ed280p-3f, 0x1.8933b0p-5f, -0x1.ab1188p-3f, 0x1.6cb664p-3f, 0x1.d31d70p-3f,
            -0x1.da6b34p-3f, 0x1.faf2f4p-3f, -0x1.2cc578p-4f, -0x1.45bcd0p-3f, -0x1.177290p-4f, -0x1.8c4690p-5f, -0x1.332900p-7f, 0x1.276d74p-3f
        },
        {
            0x1.998d70p-3f, -0x1.9c0390p-3f, -0x1.167760p-3f, 0x1.b77418p-3f, -0x1.19c6bcp-3f, -0x1.198000p-7f, 0x1.ca0ca0p-6f, 0x1.3bac80p-6f,
            0x1.49bd30p-5f, 0x1.95daf8p-4f, 0x1.d37500p-8f, 0x1.3032f0p-5f, -0x1.1d8a00p-5f, -0x1.bf3620p-3f, -0x1.3d8488p-4f, 0x1.886da0p-6f
        },
        {
            -0x1.af50d0p-4f, 0x1.f85d70p-4f, -0x1.f42b1cp-3f, -0x1.73a740p-7f, -0x1.e113c8p-3f, -0x1.456738p-4f, -0x1.2c0880p-8f, -0x1.9b62b0p-4f,
            0x1.a30d98p-4f, 0x1.9e9958p-3f, 0x1.170d88p-3f, 0x1.617b54p-3f, -0x1.11b9e0p-5f, 0x1.320e7cp-3f, -0x1.a292f8p-4f, 0x1.d56c58p-3f
        },
        {
            -0x1.ecda48p-4f, 0x1.1ec14cp-3f, 0x1.521ca4p-3f, -0x1.60d68cp-3f, -0x1.431438p-3f, 0x1.42b62cp-3f, -0x1.128840p-6f, -0x1.40e570p-4f,
            -0x1.0f6580p-5f, -0x1.c9c9a4p-3f, 0x1.d10118p-4f, 0x1.dab930p-3f, 0x1.7f4268p-4f, 0x1.b1dde0p-3f, -0x1.333c94p-3f, 0x1.5503f8p-4f
        },
        {
            0x1.1e7b64p-3f, -0x1.387dccp-3f, -0x1.df8158p-4f, 0x1.465ed0p-5f, 0x1.32fad8p-3f, 0x1.137660p-5f, -0x1.8e5e28p-3f, -0x1.37b53cp-3f,
            0x1.b70f90p-4f, 0x1.658d80p-3f, 0x1.9b9070p-4f, -0x1.1e4ec8p-4f, 0x1.49ee70p-5f, 0x1.8de728p-3f, -0x1.4b7c90p-3f, -0x1.a93d50p-5f
        },
        {
            0x1.4560f8p-3f, -0x1.163000p-13f, 0x1.24de24p-3f, -0x1.1b8080p-7f, 0x1.0e3778p-4f, -0x1.ed7750p-4f, 0x1.45f118p-4f, 0x1.f417e0p-4f,
            -0x1.1b7bf0p-3f, 0x1.ce1888p-3f, -0x1.a78688p-4f, 0x1.41a970p-4f, -0x1.72c060p-4f, -0x1.69282cp-3f, -0x1.ed7ebcp-3f, -0x1.33c580p-4f
        },
        {
            0x1.78dd20p-6f, -0x1.2ced18p-3f, -0x1.236dd4p-3f, -0x1.52e140p-3f, -0x1.727984p-3f, 0x1.ac6c0cp-3f, -0x1.e218a0p-6f, -0x1.587d00p-4f,
            -0x1.63d2e0p-3f, -0x1.439210p-4f, 0x1.8af7b0p-3f, -0x1.00061cp-3f, 0x1.32d130p-5f, 0x1.fa6f10p-3f, -0x1.a9c1a0p-6f, -0x1.582ef8p-3f
        },
        {
            -0x1.224f3cp-3f, -0x1.b35ce0p-6f, -0x1.088c80p-3f, -0x1.c5aa6cp-3f, 0x1.d3b3d4p-3f, -0x1.23b638p-4f, -0x1.9b4530p-4f, -0x1.dbdf10p-3f,
            -0x1.ff81f0p-4f, -0x1.56d4b0p-4f, 0x1.12f57cp-3f, 0x1.760cf8p-3f, 0x1.7fe258p-3f, 0x1.3f2fa0p-6f, -0x1.b69ab0p-5f, 0x1.8740c0p-5f
        },
        {
            -0x1.ecb490p-4f, 0x1.1318b4p-3f, -0x1.df7b28p-3f, 0x1.6f92f4p-3f, 0x1.e89a28p-4f, -0x1.011f88p-4f, 0x1.724128p-3f, -0x1.eb5f58p-3f,
            -0x1.b13decp-3f, -0x1.8fce60p-5f, 0x1.1220b8p-4f, 0x1.5af388p-3f, -0x1.f89cd0p-4f, -0x1.a34310p-4f, 0x1.950798p-3f, 0x1.cf8770p-5f
        },
        {
            -0x1.f847f8p-3f, -0x1.8d2f88p-3f, 0x1.cfcbecp-3f, 0x1.052108p-4f, -0x1.b753acp-3f, -0x1.7b08c0p-5f, 0x1.3f8e20p-3f, -0x1.685200p-6f,
            -0x1.21a730p-4f, -0x1.58e940p-7f, 0x1.80f9c0p-5f, -0x1.3ea440p-3f, -0x1.3e67c0p-6f, 0x1.4d4ad0p-4f, 0x1.598cc0p-5f, -0x1.70edb0p-3f
        },
        {
            -0x1.28dfa8p-3f, 0x1.36572cp-3f, 0x1.c03c78p-3f, 0x1.1ca884p-3f, 0x1.f54050p-4f, 0x1.739c98p-3f, -0x1.a299b0p-5f, -0x1.79b6c4p-3f,
            -0x1.298c20p-5f, 0x1.af1368p-3f, -0x1.1e4520p-5f, 0x1.2226a8p-3f, -0x1.89ed30p-3f, 0x1.345190p-3f, -0x1.8eb6e0p-4f, -0x1.c03bdcp-3f
        },
        {
            -0x1.df4130p-4f, -0x1.7150a8p-3f, -0x1.9585b8p-4f, 0x1.e85000p-3f, -0x1.2f0820p-6f, -0x1.6d4d1cp-3f, 0x1.7e5800p-11f, -0x1.1e918cp-3f,
            -0x1.ffead8p-3f, 0x1.30f230p-5f, -0x1.02ac00p-9f, 0x1.b2f090p-5f, 0x1.275620p-5f, 0x1.6eb1fcp-3f, -0x1.f4f990p-3f, -0x1.38076cp-3f
        },
        {
            0x1.a00790p-3f, 0x1.fed200p-4f, -0x1.6c29f8p-3f, -0x1.375230p-3f, -0x1.e9b570p-5f, 0x1.e42290p-3f, -0x1.a99f48p-3f, 0x1.da014cp-3f,
            0x1.d53d4cp-3f, 0x1.71b620p-4f, 0x1.2a6548p-3f, -0x1.863158p-3f, -0x1.9ab1f4p-3f, 0x1.edff50p-4f, 0x1.a89fa0p-5f, 0x1.07d340p-5f
        },
        {
            0x1.47c3dcp-3f, -0x1.ed58bcp-3f, -0x1.b0e688p-4f, -0x1.062ae0p-3f, 0x1.b2db40p-6f, -0x1.870b08p-4f, 0x1.554d28p-4f, -0x1.276c88p-4f,
            -0x1.b3c000p-11f, -0x1.406c50p-4f, 0x1.89ba00p-5f, 0x1.8b677cp-3f, 0x1.3e4b58p-4f, -0x1.ab6a40p-7f, 0x1.3c51f8p-4f, 0x1.f3fdd8p-3f
        },
        {
            -0x1.4576c0p-3f, 0x1.d74c90p-3f, 0x1.4dd140p-6f, 0x1.1a2940p-4f, 0x1.697180p-4f, 0x1.daf4bcp-3f, -0x1.d03f64p-3f, 0x1.d559a8p-3f,
            0x1.7022d8p-3f, 0x1.73e2e0p-4f, 0x1.867e48p-4f, -0x1.c6c228p-3f, -0x1.fb2ab8p-4f, -0x1.9fabf0p-4f, -0x1.a4ab00p-5f, -0x1.0be140p-6f
        },
        {
            -0x1.351704p-3f, -0x1.50aa2cp-3f, 0x1.8cba6cp-3f, 0x1.cfdaecp-3f, -0x1.7be4c0p-6f, -0x1.9ee1a8p-4f, -0x1.0681b4p-3f, 0x1.a54084p-3f,
            -0x1.ed0900p-4f, -0x1.e42fd0p-3f, -0x1.424a40p-7f, -0x1.cdb3c4p-3f, -0x1.e6a7e0p-6f, -0x1.c94f30p-3f, -0x1.d93a00p-6f, -0x1.11e554p-3f
        },
        {
            -0x1.841becp-3f, -0x1.beb248p-4f, -0x1.7599e8p-4f, -0x1.b96410p-3f, 0x1.4ea550p-4f, 0x1.f58770p-4f, 0x1.6d0f20p-6f, 0x1.72da50p-4f,
            0x1.74b460p-4f, -0x1.38ae30p-4f, 0x1.21a288p-3f, -0x1.93e790p-5f, -0x1.899324p-3f, 0x1.59e69cp-3f, -0x1.b42400p-3f, 0x1.5440a8p-4f
        },
        {
            0x1.293fc0p-3f, 0x1.83d638p-4f, 0x1.f6db60p-4f, -0x1.41b0c0p-7f, 0x1.c9554cp-3f, 0x1.562facp-3f, 0x1.8f6f20p-5f, -0x1.bf7e60p-6f,
            0x1.911110p-5f, 0x1.305830p-3f, 0x1.5b8a20p-3f, 0x1.c48fc0p-7f, -0x1.9ecdf0p-3f, 0x1.2c8060p-4f, -0x1.398370p-3f, -0x1.e89b40p-5f
        },
        {
            0x1.d5219cp-3f, -0x1.fac560p-3f, -0x1.ac3930p-4f, 0x1.519578p-3f, -0x1.03c938p-3f, -0x1.df9f00p-6f, 0x1.cd4cf4p-3f, 0x1.441860p-6f,
            -0x1.35ddc8p-4f, -0x1.086270p-3f, 0x1.2d47c0p-7f, 0x1.5b5cb0p-4f, -0x1.57d238p-3f, 0x1.af2580p-5f, 0x1.d37efcp-3f, 0x1.a120a0p-3f
        },
        {
            0x1.f35754p-3f, -0x1.6bcfb4p-3f, 0x1.24d8a0p-5f, -0x1.1db1d0p-3f, 0x1.54ab00p-4f, -0x1.523148p-3f, -0x1.f03790p-5f, -0x1.56e4d0p-3f,
            -0x1.c34cc4p-3f, -0x1.919840p-7f, 0x1.73a334p-3f, -0x1.48fa5cp-3f, -0x1.37ce00p-10f, 0x1.f8eac8p-3f, 0x1.a5b3e8p-3f, -0x1.2b91b0p-5f
        },
        {
            -0x1.0d6fe8p-3f, -0x1.630e70p-5f, 0x1.1391c0p-6f, -0x1.66d9c0p-6f, -0x1.39e5d8p-4f, -0x1.8988c0p-4f, -0x1.9f2a08p-4f, 0x1.ce6620p-4f,
            -0x1.73b5c0p-4f, -0x1.aa1734p-3f, -0x1.51caa8p-3f, 0x1.1c4b00p-4f, -0x1.c74448p-4f, 0x1.c99620p-4f, 0x1.597160p-6f, -0x1.1cbf3cp-3f
        },
        {
            -0x1.c719b4p-3f, 0x1.5b156cp-3f, 0x1.2e8120p-5f, 0x1.11c2a4p-3f, 0x1.672920p-3f, 0x1.f997d0p-4f, 0x1.ba10fcp-3f, -0x1.7f7dc0p-5f,
            -0x1.98b2b0p-5f, 0x1.4f9aa4p-3f, 0x1.5debccp-3f, -0x1.1c7a14p-3f, -0x1.0bd2f4p-3f, 0x1.692bf8p-4f, -0x1.6ed990p-4f, -0x1.2d6b20p-3f
        },
        {
            -0x1.61b5e4p-3f, 0x1.f55578p-4f, 0x1.221478p-4f, 0x1.ce1960p-6f, 0x1.d53a94p-3f, 0x1.e192a8p-3f, -0x1.4b6014p-3f, -0x1.aade08p-4f,
            -0x1.612ea0p-3f, -0x1.ddbd08p-3f, -0x1.210790p-5f, -0x1.54e47cp-3f, 0x1.b9e480p-8f, 0x1.f6b788p-4f, 0x1.17441cp-3f, 0x1.f98ac8p-3f
        },
        {
            -0x1.06b240p-5f, 0x1.f14868p-3f, 0x1.5ee660p-4f, -0x1.7ab420p-5f, 0x1.4dcfd8p-3f, 0x1.529200p-9f, 0x1.1b5c44p-3f, 0x1.7ca680p-8f,
            0x1.64d21cp-3f, -0x1.cbf0a0p-5f, -0x1.ad3c80p-8f, -0x1.f74000p-9f, -0x1.1ff480p-7f, 0x1.81a280p-7f, 0x1.499c00p-7f, 0x1.5783a0p-4f
        },
        {
            0x1.0bc51cp-3f, 0x1.5f42c8p-3f, 0x1.0ee4ecp-3f, 0x1.95af10p-5f, -0x1.653640p-6f, 0x1.c50280p-4f, 0x1.249798p-4f, 0x1.997adcp-3f,
            -0x1.fa5b50p-4f, -0x1.25e1d0p-3f, -0x1.651260p-5f, 0x1.d11178p-3f, 0x1.059d60p-6f, -0x1.2d2304p-3f, 0x1.0ec0b0p-5f, -0x1.30cfb8p-4f
        },
        {
            0x1.054e00p-9f, 0x1.affc00p-3f, -0x1.85c6f0p-5f, 0x1.794000p-4f, -0x1.4c6120p-4f, 0x1.4fbcc8p-4f, -0x1.d6ab10p-4f, 0x1.92b078p-3f,
            -0x1.0d6bd0p-4f, 0x1.84a530p-3f, -0x1.ec3300p-3f, -0x1.610248p-4f, -0x1.bc1adcp-3f, -0x1.3f78f0p-5f, -0x1.9d46e8p-3f, -0x1.be1478p-4f
        },
        {
            0x1.b984e0p-6f, -0x1.38b304p-3f, 0x1.ca5b70p-4f, -0x1.ab968cp-3f, -0x1.47cc68p-3f, -0x1.ca7f5cp-3f, 0x1.f5a880p-8f, -0x1.3a9f40p-5f,
            0x1.42dea0p-4f, -0x1.037610p-3f, 0x1.6c5180p-7f, 0x1.a97d00p-5f, 0x1.e1b718p-4f, 0x1.38bb64p-3f, 0x1.74a640p-6f, -0x1.f97728p-3f
        },
        {
            0x1.0834d0p-3f, 0x1.33a758p-3f, -0x1.a10060p-5f, -0x1.813fecp-3f, 0x1.e8cdc0p-4f, -0x1.96e7a0p-5f, -0x1.97e4a0p-3f, 0x1.2910c0p-3f,
            0x1.28fbccp-3f, 0x1.c5b748p-3f, -0x1.939278p-4f, 0x1.7ff14cp-3f, -0x1.41ef58p-4f, 0x1.676584p-3f, 0x1.105d7cp-3f, 0x1.f36dfcp-3f
        },
        {
            0x1.a716e0p-6f, 0x1.2c2434p-3f, -0x1.6144a8p-4f, -0x1.12d360p-5f, -0x1.2914a0p-3f, -0x1.4a3f4cp-3f, 0x1.76265cp-3f, 0x1.3c24d0p-3f,
            0x1.1f6ae4p-3f, 0x1.2e1340p-7f, 0x1.4e9730p-5f, 0x1.dcdfe0p-3f, -0x1.985f78p-4f, 0x1.4db3c4p-3f, 0x1.a446c0p-3f, -0x1.7cf470p-3f
        },
        {
            0x1.abc7bcp-3f, -0x1.b4bcc0p-7f, -0x1.9a1000p-6f, 0x1.325060p-5f, -0x1.a6da90p-3f, 0x1.8de800p-7f, 0x1.081804p-3f, -0x1.cc9becp-3f,
            0x1.8f1a8cp-3f, -0x1.c51e80p-4f, -0x1.d301c0p-4f, 0x1.179e30p-4f, -0x1.db9340p-3f, -0x1.f9f1e8p-4f, 0x1.e60974p-3f, 0x1.682fa8p-3f
        },
        {
            -0x1.aec9f0p-5f, -0x1.a81b80p-7f, -0x1.0cbe80p-5f, -0x1.23c5e0p-6f, 0x1.6e16d0p-5f, 0x1.964100p-5f, -0x1.01ecf0p-4f, -0x1.d5b1c8p-4f,
            0x1.a26b14p-3f, 0x1.6e8360p-4f, 0x1.497088p-4f, -0x1.b0a368p-3f, -0x1.e187c8p-3f, -0x1.cfee48p-4f, 0x1.e6e928p-3f, -0x1.839500p-9f
        },
        {
            0x1.9ab044p-3f, -0x1.d14834p-3f, 0x1.42eb98p-4f, -0x1.ad3790p-3f, -0x1.81f7c0p-7f, 0x1.c2bb98p-3f, -0x1.c7bf60p-5f, 0x1.42cb44p-3f,
            0x1.3999b8p-3f, -0x1.dca9c0p-3f, 0x1.fb9e60p-6f, 0x1.0df980p-5f, 0x1.ee3fe0p-3f, 0x1.b05d00p-7f, 0x1.b7bc20p-6f, 0x1.304958p-4f
        },
        {
            0x1.3da2f8p-4f, 0x1.886fe0p-4f, 0x1.101d10p-5f, -0x1.31b000p-5f, -0x1.cdc0b8p-3f, 0x1.0a4168p-3f, 0x1.f28a80p-8f, -0x1.d18980p-6f,
            -0x1.71ef04p-3f, 0x1.adff18p-4f, -0x1.2fde88p-3f, -0x1.6cf720p-5f, -0x1.854290p-4f, 0x1.699304p-3f, -0x1.fed9fcp-3f, 0x1.358d60p-3f
        },
        {
            0x1.ea3394p-3f, 0x1.a5f214p-3f, -0x1.d4c1b8p-3f, -0x1.b6d2c4p-3f, -0x1.d828d0p-5f, 0x1.452c30p-5f, -0x1.d027d8p-3f, 0x1.758ec0p-4f,
            -0x1.917cc0p-6f, 0x1.c145e8p-4f, 0x1.1bdcacp-3f, 0x1.61e410p-5f, -0x1.d90bb0p-4f, 0x1.0623d8p-4f, -0x1.f61110p-3f, -0x1.9fbe54p-3f
        },
        {
            0x1.681770p-3f, -0x1.a2f334p-3f, -0x1.4d9940p-6f, -0x1.9564b8p-4f, -0x1.dd2cb8p-3f, -0x1.c17da0p-6f, -0x1.8f2058p-4f, 0x1.d34180p-4f,
            0x1.120ef8p-3f, -0x1.572d90p-3f, -0x1.d0ee44p-3f, 0x1.d67d7cp-3f, -0x1.dda5e0p-5f, -0x1.72378cp-3f, -0x1.7468b0p-4f, 0x1.e76e38p-3f
        },
        {
            -0x1.37b238p-4f, -0x1.5230d0p-5f, -0x1.76f330p-5f, 0x1.2cb478p-4f, 0x1.240464p-3f, 0x1.55b0d0p-3f, 0x1.60f534p-3f, 0x1.e932e0p-6f,
            0x1.7c73b8p-4f, 0x1.6b4c64p-3f, -0x1.22cfe0p-4f, -0x1.ea21a4p-3f, -0x1.a06e6cp-3f, -0x1.8e4e7cp-3f, 0x1.cb3144p-3f, 0x1.f7cd8cp-3f
        },
        {
            -0x1.660190p-3f, 0x1.ad2be8p-4f, 0x1.03dbf0p-3f, -0x1.63ca80p-6f, -0x1.dbb004p-3f, 0x1.5bf1a8p-3f, 0x1.4b6af0p-4f, -0x1.0829a0p-3f,
            -0x1.a90a0cp-3f, -0x1.c14724p-3f, 0x1.3d89a0p-4f, -0x1.f97e48p-4f, -0x1.a09860p-3f, -0x1.93a340p-3f, 0x1.0c4014p-3f, -0x1.abf2e8p-4f
        },
        {
            -0x1.43ed54p-3f, -0x1.a01440p-3f, 0x1.322898p-3f, 0x1.3d33d0p-5f, -0x1.f3a384p-3f, -0x1.5a841cp-3f, -0x1.540ea8p-4f, -0x1.f257dcp-3f,
            -0x1.23c2e0p-5f, -0x1.a92980p-6f, 0x1.7a38ecp-3f, -0x1.5bd400p-4f, 0x1.db4cdcp-3f, 0x1.a84d10p-3f, -0x1.52bb00p-3f, -0x1.b23710p-5f
        },
        {
            -0x1.e9b490p-4f, 0x1.9fe71cp-3f, -0x1.fe0a0cp-3f, 0x1.e96920p-5f, -0x1.9f0e74p-3f, -0x1.911ab4p-3f, -0x1.ddf8a0p-6f, -0x1.3c8bd0p-4f,
            0x1.dde66cp-3f, -0x1.dd1320p-5f, -0x1.a29b30p-5f, -0x1.628760p-3f, -0x1.1d6488p-4f, -0x1.54ddc8p-4f, 0x1.99b080p-3f, 0x1.5475a0p-4f
        },
        {
            0x1.cf1d48p-4f, -0x1.dc5eb8p-4f, -0x1.b707f8p-4f, 0x1.5eacb0p-3f, 0x1.b72540p-7f, 0x1.c235a0p-4f, -0x1.0ce4e8p-4f, 0x1.aaf8b0p-5f,
            0x1.3679d4p-3f, 0x1.502360p-4f, -0x1.a2d9a4p-3f, 0x1.13df60p-6f, -0x1.999b10p-3f, 0x1.7d5d54p-3f, -0x1.f4dd18p-3f, 0x1.6663a0p-6f
        },
        {
            -0x1.4c0a98p-4f, 0x1.d49cc0p-4f, -0x1.7168acp-3f, 0x1.f3ba8cp-3f, -0x1.b13ff0p-5f, -0x1.6dc1e0p-5f, -0x1.ba06a0p-3f, -0x1.9d3578p-4f,
            0x1.888784p-3f, -0x1.b79578p-3f, -0x1.436640p-4f, 0x1.5f94a0p-3f, -0x1.873824p-3f, -0x1.62e2dcp-3f, 0x1.56b068p-4f, 0x1.1e82b0p-5f
        },
        {
            0x1.d68ed4p-3f, -0x1.c07cc4p-3f, 0x1.553c34p-3f, -0x1.6c9140p-3f, 0x1.60b220p-4f, 0x1.bca7a0p-3f, 0x1.676cf0p-4f, -0x1.2aea5cp-3f,
            -0x1.8a7d40p-5f, 0x1.38c178p-4f, -0x1.9de498p-4f, 0x1.f38534p-3f, 0x1.de12b0p-3f, 0x1.0f7e20p-6f, 0x1.d77608p-4f, -0x1.e2a4e0p-5f
        },
        {
            -0x1.1e0cd8p-3f, -0x1.12f670p-4f, 0x1.06e92cp-3f, 0x1.1bb218p-3f, 0x1.835560p-5f, 0x1.4855d8p-4f, -0x1.6998b0p-5f, 0x1.f91d00p-8f,
            -0x1.09e96cp-3f, -0x1.d03738p-4f, -0x1.dce1c0p-4f, -0x1.81a180p-5f, -0x1.25f464p-3f, -0x1.4012f0p-5f, 0x1.451090p-5f, 0x1.6f05bcp-3f
        },
        {
            -0x1.d13e50p-4f, -0x1.55f40cp-3f, -0x1.a835e0p-4f, -0x1.604400p-7f, 0x1.cf5cf8p-3f, 0x1.649b34p-3f, -0x1.608b78p-4f, 0x1.0f0450p-4f,
            0x1.154640p-5f, 0x1.4bf250p-5f, -0x1.a60270p-5f, -0x1.150b14p-3f, -0x1.4ec768p-4f, -0x1.b19664p-3f, -0x1.359898p-3f, 0x1.0d21c4p-3f
        },
        {
            0x1.f35eccp-3f, -0x1.987990p-3f, -0x1.dcc554p-3f, -0x1.dc1bb0p-3f, -0x1.ef1690p-4f, -0x1.664b70p-4f, 0x1.4e29a0p-6f, -0x1.b3185cp-3f,
            0x1.063248p-3f, -0x1.b8b0a8p-3f, 0x1.62baf0p-4f, -0x1.184f98p-3f, -0x1.227af8p-4f, -0x1.23bd40p-6f, -0x1.d51908p-3f, 0x1.594b80p-8f
        },
        {
            0x1.75b190p-5f, -0x1.c184e0p-5f, -0x1.4cdcf4p-3f, -0x1.7882dcp-3f, 0x1.1e39e8p-4f, -0x1.113144p-3f, 0x1.aabb90p-4f, 0x1.2c5da0p-3f,
            0x1.61fd80p-6f, 0x1.f4ef80p-7f, 0x1.ed7d20p-4f, 0x1.2735f8p-3f, 0x1.ea8820p-5f, -0x1.a03498p-3f, 0x1.043398p-4f, 0x1.17db00p-9f
        },
        {
            0x1.9f4eb8p-4f, 0x1.4b58c0p-4f, -0x1.a3ce14p-3f, 0x1.092c18p-4f, 0x1.bd9178p-4f, 0x1.d91554p-3f, 0x1.8aaca0p-4f, 0x1.7b3c70p-5f,
            -0x1.32b020p-3f, -0x1.db7dc0p-3f, 0x1.b920b0p-5f, 0x1.9de518p-3f, -0x1.771fb0p-3f, -0x1.d2a1b4p-3f, 0x1.9110a8p-3f, -0x1.168cc8p-3f
        },
        {
            -0x1.72a4a0p-5f, -0x1.a3d310p-4f, -0x1.4f03b0p-3f, 0x1.7b0d00p-5f, 0x1.1d3004p-3f, 0x1.201998p-4f, 0x1.314448p-4f, -0x1.51b3f8p-4f,
            -0x1.8f8688p-4f, 0x1.6e0ba0p-5f, 0x1.67f5e0p-4f, -0x1.d3cac0p-3f, -0x1.89e4f0p-3f, 0x1.316fccp-3f, -0x1.796400p-9f, -0x1.1c850cp-3f
        },
        {
            0x1.0a5250p-5f, 0x1.ccf760p-4f, -0x1.8934ecp-3f, -0x1.c39d80p-8f, -0x1.e98a48p-3f, 0x1.5ac2a8p-4f, -0x1.cf1ba0p-3f, -0x1.6a7110p-4f,
            0x1.7f5e30p-4f, -0x1.de6c60p-4f, -0x1.9c2e04p-3f, -0x1.3d8e38p-4f, 0x1.b95e08p-3f, 0x1.8316e0p-4f, 0x1.032300p-6f, -0x1.f5c900p-5f
        },
        {
            -0x1.3f9354p-3f, 0x1.aa0f2cp-3f, -0x1.078f90p-5f, 0x1.618be0p-5f, -0x1.006b88p-3f, 0x1.8ddd20p-3f, -0x1.01f2d4p-3f, -0x1.1489d0p-4f,
            -0x1.f6e100p-5f, 0x1.a32140p-7f, 0x1.9b2628p-4f, 0x1.6b1408p-4f, -0x1.410440p-3f, 0x1.d5fec0p-4f, -0x1.cd0900p-9f, 0x1.72afd4p-3f
        },
        {
            0x1.947f80p-4f, 0x1.ddba60p-6f, 0x1.43a56cp-3f, -0x1.172f68p-3f, 0x1.54ce50p-4f, -0x1.49ad90p-5f, 0x1.5d6ac0p-3f, 0x1.33b060p-6f,
            -0x1.077b60p-6f, -0x1.600b78p-4f, 0x1.c91438p-3f, -0x1.1abaf0p-4f, 0x1.224f98p-3f, 0x1.aace80p-7f, 0x1.f205d0p-3f, 0x1.c39208p-4f
        },
        {
            -0x1.cf2bc0p-5f, 0x1.66c620p-6f, 0x1.3c6630p-4f, 0x1.309014p-3f, -0x1.b64c20p-4f, 0x1.ddcae8p-3f, 0x1.a0b17cp-3f, -0x1.d9b348p-4f,
            -0x1.598fe0p-5f, -0x1.b4bc18p-3f, 0x1.f9c9c8p-3f, 0x1.714890p-3f, -0x1.f30128p-3f, -0x1.372df0p-3f, 0x1.38c58cp-3f, 0x1.44c840p-6f
        },
        {
            0x1.76515cp-3f, -0x1.ae9d00p-7f, 0x1.ca7ca8p-4f, 0x1.31494cp-3f, 0x1.aaefc8p-3f, -0x1.f89c50p-4f, -0x1.ae3700p-7f, -0x1.5d22a0p-5f,
            0x1.971d80p-4f, -0x1.707d94p-3f, -0x1.118b64p-3f, -0x1.f400f8p-3f, 0x1.f38cf0p-4f, 0x1.f8d0a8p-3f, -0x1.8e5808p-4f, 0x1.480ea0p-5f
        },
        {
            0x1.d6ea78p-4f, -0x1.47c8a0p-4f, 0x1.76f68cp-3f, -0x1.0e56a8p-4f, -0x1.5cdf10p-4f, -0x1.ba41d0p-5f, 0x1.4c515cp-3f, -0x1.06e7a4p-3f,
            -0x1.c3d020p-6f, -0x1.f7134cp-3f, -0x1.895e80p-5f, -0x1.5260b0p-4f, -0x1.c3cd24p-3f, -0x1.193650p-5f, -0x1.2ca4a0p-5f, -0x1.fbaf0cp-3f
        },
        {
            -0x1.a27078p-4f, -0x1.afb084p-3f, 0x1.c386d0p-5f, 0x1.cf5810p-5f, 0x1.21d970p-4f, -0x1.107770p-4f, -0x1.87a530p-3f, 0x1.62e948p-4f,
            0x1.da6714p-3f, -0x1.d39eccp-3f, -0x1.296528p-3f, -0x1.852218p-4f, 0x1.149080p-7f, 0x1.a26f90p-4f, -0x1.85a9fcp-3f, 0x1.e15740p-6f
        }
    }
};

/*
 * Weight 3:
 * Name: weight3_onnx__lstm_109
 * Shape: (1, 128)
 * Elements: 128
 * Dtype: float
 */
static const float weight3_onnx__lstm_109[1][128] = {
    {
        -0x1.1d7bf4p-3f, 0x1.966c48p-4f, -0x1.2703f0p-4f, 0x1.233050p-4f, -0x1.1f4454p-3f, -0x1.4269a8p-3f, 0x1.6d18f8p-4f, -0x1.ebb650p-5f,
        -0x1.720060p-6f, -0x1.87d490p-3f, 0x1.832a58p-3f, 0x1.c576b8p-3f, -0x1.6ae9b0p-4f, 0x1.ed5de0p-4f, 0x1.c91b70p-4f, 0x1.fcc234p-3f,
        0x1.a45138p-3f, -0x1.c342a0p-6f, -0x1.699498p-3f, 0x1.baacc0p-3f, -0x1.8dd6a0p-5f, 0x1.9abe98p-4f, 0x1.3c08e0p-3f, -0x1.2e9694p-3f,
        -0x1.717420p-5f, 0x1.90186cp-3f, 0x1.d7f5e0p-6f, 0x1.8459bcp-3f, 0x1.7b4d08p-3f, 0x1.ecbf80p-6f, -0x1.f3b940p-6f, 0x1.0df820p-5f,
        0x1.522228p-4f, -0x1.3a4ff0p-3f, 0x1.82f904p-3f, -0x1.775a68p-4f, 0x1.c57878p-3f, -0x1.523800p-12f, 0x1.b9b4c8p-3f, -0x1.1ca430p-5f,
        -0x1.b51c40p-7f, 0x1.b50c8cp-3f, 0x1.11e7b4p-3f, -0x1.53c378p-3f, -0x1.05dce0p-5f, -0x1.fdf128p-4f, -0x1.43a928p-4f, 0x1.7b9e20p-4f,
        -0x1.e70970p-3f, -0x1.cc407cp-3f, 0x1.dd93a8p-3f, 0x1.c64658p-3f, 0x1.c86f14p-3f, 0x1.4b7c18p-4f, 0x1.bf670cp-3f, 0x1.9786f0p-3f,
        -0x1.66ced0p-4f, -0x1.137664p-3f, 0x1.04cd50p-4f, -0x1.d724d0p-4f, 0x1.06e200p-5f, 0x1.98a3c0p-4f, -0x1.c06b10p-5f, -0x1.bd25b0p-4f,
        -0x1.b6a030p-5f, -0x1.9c1160p-5f, -0x1.5889d4p-3f, -0x1.fdff40p-7f, -0x1.6aac04p-3f, 0x1.d34a48p-4f, 0x1.802cf4p-3f, -0x1.04e0f4p-3f,
        -0x1.a41910p-5f, 0x1.4ebcf0p-3f, -0x1.e0bff8p-3f, -0x1.eb2500p-4f, 0x1.2b9888p-4f, -0x1.c8a2e0p-6f, 0x1.50d60cp-3f, 0x1.48b200p-6f,
        0x1.238258p-4f, -0x1.d8fe64p-3f, 0x1.587270p-3f, -0x1.c7a200p-4f, 0x1.56ee50p-3f, 0x1.1bdad4p-3f, -0x1.fe5248p-4f, 0x1.f0f500p-8f,
        -0x1.545660p-3f, 0x1.52191cp-3f, -0x1.8d3d00p-6f, 0x1.d18c1cp-3f, 0x1.2a9318p-3f, -0x1.5d6748p-3f, -0x1.e2a300p-5f, -0x1.2b9360p-3f,
        0x1.c88a98p-3f, -0x1.6da710p-5f, -0x1.b36bfcp-3f, -0x1.a60fc0p-5f, -0x1.422ed4p-3f, 0x1.604ea0p-3f, -0x1.2bcc80p-3f, -0x1.d9fe8cp-3f,
        -0x1.25c230p-5f, -0x1.2e6c20p-4f, -0x1.db2db0p-5f, 0x1.ca7cc4p-3f, -0x1.11f344p-3f, -0x1.6b9418p-4f, 0x1.b36930p-3f, -0x1.4dc24cp-3f,
        -0x1.153280p-4f, 0x1.349734p-3f, 0x1.00c980p-4f, -0x1.486bd8p-3f, 0x1.9cebe0p-6f, -0x1.d43cb8p-3f, 0x1.ef85c4p-3f, -0x1.b7cb88p-4f,
        0x1.0f1220p-6f, -0x1.f92628p-3f, -0x1.2c6070p-5f, -0x1.bfce00p-6f, 0x1.2079d8p-3f, -0x1.e8ef70p-3f, 0x1.b66cc0p-5f, -0x1.70e930p-5f
    }
};

/*
 * Weight 4:
 * Name: weight4__lstm_expand_output_0
 * Shape: (1, 1, 16)
 * Elements: 16
 * Dtype: float
 */
static const float weight4__lstm_expand_output_0[1][1][16] = {
    {
        {
            0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f,
            0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f, 0x0.0p+0f
        }
    }
};

/*
 * Weight 5:
 * Name: weight5__constant_output_0
 * Shape: []
 * Elements: 1
 * Dtype: int64
 */
static const int64_t weight5__constant_output_0[1] = {
    -1LL
};

/*
 * Weight 6:
 * Name: weight6_fc_weight
 * Shape: (1, 16)
 * Elements: 16
 * Dtype: float
 */
static const float weight6_fc_weight[1][16] = {
    {
        0x1.706678p-3f, -0x1.e7e0d4p-3f, -0x1.3feb60p-6f, 0x1.4e3c4cp-3f, -0x1.f55724p-3f, 0x1.186428p-4f, -0x1.c421fcp-3f, -0x1.d4ab60p-3f,
        0x1.0394c0p-6f, 0x1.2daf10p-4f, 0x1.4b9ae0p-4f, -0x1.97a3dcp-3f, 0x1.1e0138p-3f, -0x1.5b5cc0p-6f, 0x1.89cee0p-4f, 0x1.234a50p-3f
    }
};

/*
 * Weight 7:
 * Name: weight7_fc_bias
 * Shape: (1,)
 * Elements: 1
 * Dtype: float
 */
static const float weight7_fc_bias[1] = {
    0x1.4a0448p-4f
};

static inline float ref_scalar_f32_sigmoid(float a) {
    return 1.0f / (1.0f + expf(-a));
}

static inline float ref_scalar_f32_tanh(float a) {
    return tanhf(a);
}

/*
 * Node 0:
 * OpType: Transpose
 * Name: /lstm/Transpose
 * Inputs: input
 * Outputs: /lstm/Transpose_output_0
 * Attrs:
 *   perm: [1, 0, 2]
 */
static inline void node0__lstm_transpose(const float input0[restrict 1][10][3], float output[restrict 10][1][3]) {
    for (idx_t i0 = 0; i0 < 10; ++i0) {
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            for (idx_t i2 = 0; i2 < 3; ++i2) {
                output[i0][i1][i2] = input0[i1][i0][i2];
            }
        }
    }
}

/*
 * Node 1:
 * OpType: LSTM
 * Name: /lstm/LSTM
 * Inputs: /lstm/Transpose_output_0, onnx::LSTM_107, onnx::LSTM_108, onnx::LSTM_109, , /lstm/Expand_output_0, /lstm/Expand_output_0
 * Outputs: /lstm/LSTM_output_0, /lstm/LSTM_output_1, /lstm/LSTM_output_2
 * Attrs:
 *   hidden_size: 16
 */
static inline void node1__lstm_lstm(const float input_x[restrict 10][1][3], const float input_w[restrict 1][64][3], const float input_r[restrict 1][64][16], const float input_b[restrict 1][128], const float input_initial_h[restrict 1][1][16], const float input_initial_c[restrict 1][1][16], float output_y[restrict 10][1][1][16], float output_y_h[restrict 1][1][16], float output_y_c[restrict 1][1][16]) {
    {
        const int dir = 0;
        const int reverse = 0;
        float H_prev[1][16];
        float C_prev[1][16];
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 16; ++h) {
                H_prev[b][h] = input_initial_h[dir][b][h];
                C_prev[b][h] = input_initial_c[dir][b][h];
            }
        }
        for (int b = 0; b < 1; ++b) {
            int seq_limit = 10;
            for (int step = 0; step < seq_limit; ++step) {
                int t = reverse ? (10 - 1 - step) : step;
                float H_next[16];
                float C_next[16];
                for (int h = 0; h < 16; ++h) {
                    float gate_i = 0.0f;
                    float gate_o = 0.0f;
                    float gate_f = 0.0f;
                    float gate_c = 0.0f;
                    for (int i = 0; i < 3; ++i) {
                        float x_val = input_x[t][b][i];
                        gate_i += x_val * input_w[dir][h][i];
                        gate_o += x_val * input_w[dir][16 + h][i];
                        gate_f += x_val * input_w[dir][16 * 2 + h][i];
                        gate_c += x_val * input_w[dir][16 * 3 + h][i];
                    }
                    for (int i = 0; i < 16; ++i) {
                        float h_val = H_prev[b][i];
                        gate_i += h_val * input_r[dir][h][i];
                        gate_o += h_val * input_r[dir][16 + h][i];
                        gate_f += h_val * input_r[dir][16 * 2 + h][i];
                        gate_c += h_val * input_r[dir][16 * 3 + h][i];
                    }
                    gate_i += input_b[dir][h] + input_b[dir][16 * 4 + h];
                    gate_o += input_b[dir][16 + h] + input_b[dir][16 * 5 + h];
                    gate_f += input_b[dir][16 * 2 + h] + input_b[dir][16 * 6 + h];
                    gate_c += input_b[dir][16 * 3 + h] + input_b[dir][16 * 7 + h];
                    float i_gate = ref_scalar_f32_sigmoid(gate_i);
                    float f_gate = ref_scalar_f32_sigmoid(gate_f);
                    float c_gate = ref_scalar_f32_tanh(gate_c);
                    float c_new = f_gate * C_prev[b][h] + i_gate * c_gate;
                    float o_gate = ref_scalar_f32_sigmoid(gate_o);
                    float h_new = o_gate * ref_scalar_f32_tanh(c_new);
                    C_next[h] = c_new;
                    H_next[h] = h_new;
                    output_y[step][dir][b][h] = h_new;
                }
                for (int h = 0; h < 16; ++h) {
                    C_prev[b][h] = C_next[h];
                    H_prev[b][h] = H_next[h];
                }
            }
            for (int step = seq_limit; step < 10; ++step) {
                for (int h = 0; h < 16; ++h) {
                    output_y[step][dir][b][h] = 0.0f;
                }
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 16; ++h) {
                output_y_h[dir][b][h] = H_prev[b][h];
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 16; ++h) {
                output_y_c[dir][b][h] = C_prev[b][h];
            }
        }
    }
}

/*
 * Node 2:
 * OpType: Gather
 * Name: /Gather
 * Inputs: /lstm/LSTM_output_1, /Constant_output_0
 * Outputs: /Gather_output_0
 * Attrs:
 *   axis: 0
 */
static inline void node2__gather(const float data[restrict 1][1][16], const int64_t indices[restrict 1], float output[restrict 1][16]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 16; ++i1) {
            idx_t gather_index = indices[0];
            if (gather_index < 0) {
                gather_index += 1;
            }
            output[i0][i1] = data[gather_index][i0][i1];
        }
    }
}

/*
 * Node 3:
 * OpType: Gemm
 * Name: /fc/Gemm
 * Inputs: /Gather_output_0, fc.weight, fc.bias
 * Outputs: soc_output
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 *   transB: 1
 */
static inline void node3__fc_gemm(const float input_a[restrict 1][16], const float input_b[restrict 1][16], const float input_c[restrict 1], float output[restrict 1][1]) {
    for (idx_t i = 0; i < 1; ++i) {
        for (idx_t j = 0; j < 1; ++j) {
            float acc = 0.0f;
            for (idx_t k = 0; k < 16; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[j][k];
                acc += a_val * b_val;
            }
            idx_t c_j = 0;
            const float bias = input_c[c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

void model(const float input[restrict 1][10][3], float soc_output[restrict 1][1]) {
    float tmp0__lstm_Transpose_output_0[10][1][3];
    float tmp1__lstm_LSTM_output_0[10][1][1][16];
    float tmp2__lstm_LSTM_output_1[1][1][16];
    float tmp3__lstm_LSTM_output_2[1][1][16];
    float tmp4__Gather_output_0[1][16];
    node0__lstm_transpose(input, tmp0__lstm_Transpose_output_0);
    node1__lstm_lstm(tmp0__lstm_Transpose_output_0, weight1_onnx__lstm_107, weight2_onnx__lstm_108, weight3_onnx__lstm_109, weight4__lstm_expand_output_0, weight4__lstm_expand_output_0, tmp1__lstm_LSTM_output_0, tmp2__lstm_LSTM_output_1, tmp3__lstm_LSTM_output_2);
    node2__gather(tmp2__lstm_LSTM_output_1, weight5__constant_output_0, tmp4__Gather_output_0);
    node3__fc_gemm(tmp4__Gather_output_0, weight6_fc_weight, weight7_fc_bias, soc_output);
}

static uint64_t rng_state = 0x243f6a8885a308d3ull;

static uint64_t rng_next_u64(void) {
    uint64_t x = rng_state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    rng_state = x;
    return x * 0x2545f4914f6cdd1dull;
}

static float rng_next_float(void) {
    return (float)((double)rng_next_u64() * (1.0 / 18446744073709551616.0));
}

static double rng_next_double(void) {
    return (double)rng_next_u64() * (1.0 / 18446744073709551616.0);
}

static int64_t rng_next_i64(void) {
    return (int64_t)rng_next_u64();
}


int main(void) {

    float input[1][10][3];
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 10; ++i1) {
            for (idx_t i2 = 0; i2 < 3; ++i2) {
                input[i0][i1][i2] = rng_next_float();
            }
        }
    }

    float soc_output[1][1];

    model(input, soc_output);

    printf("{\"inputs\":{");
    printf("\"input\":{\"shape\":[1,10,3],\"data\":");
    printf("[");
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        if (i0) {
            printf(",");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 10; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 3; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("%.8g", (double)input[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");

    printf("},\"outputs\":{");
    printf("\"soc_output\":{\"shape\":[1,1],\"data\":");
    printf("[");
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        if (i0) {
            printf(",");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("%.8g", (double)soc_output[i0][i1]);
        }
        printf("]");
    }
    printf("]}");
    printf("}}\n");
    return 0;
}
