/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Command line: compile infineon_fully_connected_model.onnx
 * Model checksum (sha256): 440ac02e4384d92a436bc8f509a79f87a68ff7bb172cd6148a16521f39935276
 * Model name: infineon_fully_connected_model
 * Graph name: torch_jit
 * Inputs: 1 Outputs: 1 Nodes: 7 Initializers: 8
 * IR version: 6
 * Model version: n/a
 * Domain: n/a
 * Producer: pytorch (version: 1.13.1)
 * Opset imports: ai.onnx=11
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif

/*
 * Weight 1:
 * Name: weight1_fc1_weight
 * Shape: (12, 6)
 * Elements: 72
 * Dtype: float
 */
static const float weight1_fc1_weight[12][6] = {
    {
        0x1.92b940p-6f, -0x1.545b60p-2f, 0x1.367d2cp-2f, -0x1.432cd8p-3f, -0x1.986428p-2f, 0x1.6840b8p-3f
    },
    {
        0x1.478a44p-2f, 0x1.075444p-2f, -0x1.18c058p-2f, -0x1.08fc0cp-3f, -0x1.862b80p-4f, 0x1.093348p-3f
    },
    {
        0x1.6ba798p-2f, 0x1.5e0124p-2f, -0x1.21ac70p-3f, -0x1.e200e8p-4f, -0x1.457a20p-3f, 0x1.5d5ca0p-4f
    },
    {
        -0x1.9d4732p-2f, -0x1.99c800p-11f, -0x1.306654p-3f, 0x1.10ee00p-10f, 0x1.f5e1d0p-3f, -0x1.96cec0p-6f
    },
    {
        -0x1.e5ef68p-3f, 0x1.b85130p-3f, 0x1.e474f0p-4f, -0x1.99ed8ep-3f, 0x1.c62870p-3f, -0x1.3d38b4p-2f
    },
    {
        -0x1.634cb4p-3f, 0x1.a15ba4p-2f, 0x1.1415ecp-2f, 0x1.704158p-2f, 0x1.4657f8p-2f, 0x1.ae6770p-4f
    },
    {
        0x1.441bd4p-2f, 0x1.8842e0p-4f, -0x1.a988e0p-5f, 0x1.d919c0p-4f, 0x1.a48400p-4f, 0x1.50e930p-2f
    },
    {
        0x1.0e51c8p-2f, 0x1.6bdd28p-3f, -0x1.3a9c40p-6f, -0x1.61c692p-3f, -0x1.5d8440p-7f, -0x1.b58396p-3f
    },
    {
        0x1.7e4690p-4f, 0x1.ee31d0p-3f, 0x1.5020a0p-2f, -0x1.2e1a2ap-2f, 0x1.51db90p-3f, 0x1.7cd068p-3f
    },
    {
        -0x1.667b18p-4f, -0x1.a15bdcp-3f, 0x1.09ea58p-4f, 0x1.cd5658p-3f, -0x1.715d50p-2f, 0x1.470d50p-4f
    },
    {
        -0x1.cb5898p-4f, 0x1.23d3b8p-3f, -0x1.bc4a9ep-3f, 0x1.43e224p-2f, 0x1.880c10p-2f, 0x1.47b6d0p-3f
    },
    {
        0x1.829d1cp-2f, -0x1.b99240p-3f, -0x1.5c20e8p-4f, -0x1.4f0d3ap-3f, -0x1.e83ef0p-5f, -0x1.38bd70p-4f
    }
};

/*
 * Weight 2:
 * Name: weight2_fc1_bias
 * Shape: (12,)
 * Elements: 12
 * Dtype: float
 */
static const float weight2_fc1_bias[12] = {
    0x1.ddbe18p-3f, 0x1.00cb90p-4f, -0x1.722826p-2f, -0x1.015358p-4f, 0x1.f9d670p-3f, 0x1.625cc4p-2f, 0x1.242ec0p-4f, -0x1.0274f0p-3f,
    0x1.651c00p-4f, 0x1.6e8844p-2f, -0x1.e8d6a8p-4f, -0x1.9347ccp-2f
};

/*
 * Weight 3:
 * Name: weight3_fc2_weight
 * Shape: (24, 12)
 * Elements: 288
 * Dtype: float
 */
static const float weight3_fc2_weight[24][12] = {
    {
        0x1.299de8p-4f, 0x1.c6aa90p-5f, 0x1.a03980p-7f, 0x1.2a2100p-8f, 0x1.751680p-4f, 0x1.035e48p-4f, 0x1.8a7710p-4f, -0x1.0ae65ap-3f,
        0x1.e9bcf8p-3f, 0x1.7623b4p-3f, 0x1.930120p-4f, 0x1.3bae2cp-3f
    },
    {
        0x1.544ec8p-3f, -0x1.cf6048p-3f, 0x1.742580p-3f, -0x1.07f530p-4f, 0x1.febe98p-4f, 0x1.a98af0p-3f, 0x1.978744p-3f, 0x1.4a7c00p-6f,
        -0x1.9242e0p-6f, -0x1.62ba68p-3f, 0x1.104ebcp-2f, 0x1.b35000p-10f
    },
    {
        0x1.616818p-4f, 0x1.8ad788p-4f, 0x1.b2ebe8p-4f, -0x1.0ce716p-2f, 0x1.992a08p-4f, 0x1.f15f98p-4f, 0x1.1e7b64p-2f, -0x1.4ab8eep-3f,
        0x1.180250p-3f, 0x1.b7d040p-5f, -0x1.1bda92p-2f, -0x1.c6e04cp-3f
    },
    {
        -0x1.105a20p-6f, 0x1.0b719cp-2f, -0x1.6aa820p-3f, 0x1.8160c0p-4f, 0x1.525434p-3f, 0x1.558634p-3f, 0x1.67db20p-4f, 0x1.7f0900p-8f,
        -0x1.1b2694p-2f, 0x1.20dfccp-2f, -0x1.277f26p-2f, -0x1.71d1e8p-5f
    },
    {
        -0x1.5f9780p-4f, -0x1.321dd0p-4f, -0x1.d5cbc4p-4f, -0x1.3a33bcp-3f, -0x1.e23280p-4f, -0x1.58de20p-3f, -0x1.59f908p-4f, 0x1.95c12cp-3f,
        0x1.6d8c00p-10f, -0x1.355620p-5f, 0x1.ed6580p-3f, 0x1.0482ccp-3f
    },
    {
        -0x1.74d0e0p-3f, 0x1.165c90p-2f, 0x1.faebc8p-3f, -0x1.10d740p-2f, 0x1.3bfcb0p-4f, -0x1.c6d800p-6f, -0x1.135716p-2f, -0x1.48f338p-4f,
        0x1.6eaa04p-3f, 0x1.6e94d8p-4f, -0x1.031c1ep-3f, -0x1.93d9d8p-3f
    },
    {
        -0x1.58ce4ap-3f, 0x1.fa2c80p-6f, -0x1.82dd80p-8f, -0x1.0ea92ap-2f, -0x1.9c7584p-3f, -0x1.d8699cp-3f, -0x1.030ebcp-2f, 0x1.ff1578p-4f,
        -0x1.bf4a58p-4f, -0x1.ffa9ccp-3f, -0x1.b21038p-3f, 0x1.025110p-5f
    },
    {
        0x1.9e1c08p-3f, -0x1.15bd0cp-4f, -0x1.8cbc20p-5f, -0x1.b4a020p-6f, 0x1.972620p-4f, -0x1.8f6c00p-6f, -0x1.916feap-3f, 0x1.3b29e8p-4f,
        0x1.bbad70p-5f, -0x1.94f7a4p-4f, 0x1.cd6ce8p-3f, 0x1.59167cp-3f
    },
    {
        0x1.9782b0p-5f, -0x1.7df740p-4f, -0x1.0cf224p-2f, -0x1.7bbc54p-3f, -0x1.9083a8p-3f, 0x1.37ec18p-4f, -0x1.0eb9dcp-2f, 0x1.1eb620p-2f,
        0x1.fc5d08p-4f, 0x1.6f21f0p-4f, -0x1.e44688p-4f, 0x1.ac1790p-5f
    },
    {
        -0x1.a1058cp-4f, 0x1.20dfecp-2f, 0x1.1a3fc0p-2f, 0x1.2172acp-3f, 0x1.17c0a0p-3f, 0x1.c66618p-3f, 0x1.9f095cp-3f, 0x1.430d28p-4f,
        0x1.04b748p-3f, -0x1.f1ebd0p-5f, 0x1.5772c4p-3f, 0x1.6d7100p-6f
    },
    {
        0x1.416358p-4f, 0x1.c1b010p-4f, -0x1.565df0p-3f, -0x1.938088p-3f, -0x1.3f7b88p-3f, -0x1.2f45e0p-5f, -0x1.cfd274p-3f, -0x1.4c6ec4p-4f,
        0x1.468d00p-4f, 0x1.21b2f8p-3f, 0x1.557728p-3f, 0x1.65acc0p-7f
    },
    {
        0x1.6bf5d8p-4f, 0x1.c8eec0p-3f, 0x1.179508p-2f, 0x1.e62110p-5f, -0x1.b0b59cp-3f, -0x1.3e9050p-4f, -0x1.038750p-5f, 0x1.cd8280p-5f,
        0x1.c161c0p-7f, -0x1.94ca38p-5f, -0x1.830632p-3f, -0x1.1422a4p-2f
    },
    {
        0x1.40de60p-6f, 0x1.5c1ac0p-3f, -0x1.9c753ap-3f, -0x1.6acc64p-4f, 0x1.b46b50p-3f, 0x1.2ca320p-6f, -0x1.b0f948p-5f, 0x1.1ac62cp-2f,
        -0x1.09d7ecp-4f, 0x1.6daae0p-5f, 0x1.10ad90p-5f, 0x1.cb7b20p-6f
    },
    {
        0x1.5a9788p-3f, 0x1.8447ecp-3f, 0x1.9f47b0p-3f, -0x1.bc9cd0p-3f, 0x1.523190p-3f, -0x1.c2b6bcp-4f, -0x1.0dc684p-2f, 0x1.5ec2f8p-4f,
        0x1.60e498p-4f, -0x1.16ca00p-5f, -0x1.d4cee0p-4f, -0x1.09fb60p-2f
    },
    {
        -0x1.165180p-8f, -0x1.072916p-2f, -0x1.1350ecp-2f, 0x1.ef1d78p-4f, -0x1.fedde8p-3f, -0x1.f4ac60p-4f, -0x1.02dd80p-5f, -0x1.8016b8p-4f,
        0x1.c82f20p-4f, 0x1.a30968p-4f, -0x1.a71864p-3f, 0x1.21e8f8p-4f
    },
    {
        -0x1.1d462cp-2f, 0x1.c70ca8p-3f, 0x1.a8c170p-3f, 0x1.0c9dc8p-4f, -0x1.4a8538p-5f, -0x1.ee40e8p-3f, 0x1.3be0d8p-4f, 0x1.07b810p-4f,
        0x1.9215acp-3f, -0x1.db88d4p-3f, 0x1.29a9c0p-7f, 0x1.2b8a68p-4f
    },
    {
        0x1.038d00p-3f, -0x1.15d2dcp-3f, -0x1.237008p-3f, -0x1.ab4294p-3f, -0x1.8bd67cp-3f, -0x1.040df8p-3f, -0x1.a476b0p-4f, -0x1.6364b2p-3f,
        0x1.63a160p-6f, -0x1.bdcb00p-9f, -0x1.ccaff4p-3f, 0x1.257588p-2f
    },
    {
        0x1.10426cp-3f, -0x1.a4869cp-4f, -0x1.b61978p-3f, 0x1.f7c698p-3f, 0x1.bfe588p-3f, -0x1.56f4a8p-3f, 0x1.9d042cp-3f, 0x1.1282d4p-2f,
        0x1.d4c138p-4f, -0x1.ff7d24p-3f, 0x1.db81c0p-3f, -0x1.5c46b0p-3f
    },
    {
        0x1.042b4cp-2f, -0x1.f58728p-4f, -0x1.e3f876p-3f, 0x1.238a40p-3f, -0x1.fe48bcp-3f, 0x1.429b00p-4f, 0x1.e7ce30p-3f, -0x1.e95cb8p-5f,
        -0x1.172530p-2f, 0x1.0cf890p-4f, 0x1.def808p-4f, -0x1.25d0e8p-4f
    },
    {
        0x1.2490a8p-2f, 0x1.9239f0p-4f, 0x1.949248p-4f, -0x1.849474p-3f, -0x1.49e662p-3f, -0x1.56a632p-3f, -0x1.8dcc1cp-3f, -0x1.58b7a0p-5f,
        -0x1.0a2622p-2f, 0x1.2a9a80p-5f, 0x1.db38e0p-5f, 0x1.827d60p-4f
    },
    {
        0x1.1474b8p-4f, -0x1.3c4fe6p-3f, 0x1.3c0df0p-4f, -0x1.fe1e70p-5f, -0x1.12398ep-2f, -0x1.9a3a24p-3f, 0x1.855decp-3f, 0x1.1a7260p-3f,
        0x1.f7b638p-3f, 0x1.4df864p-3f, 0x1.aaa7a0p-5f, 0x1.35fa24p-3f
    },
    {
        0x1.bfcae8p-3f, 0x1.a74a30p-4f, -0x1.8b4b80p-4f, 0x1.48a838p-4f, 0x1.ce4ee8p-3f, 0x1.c05f40p-7f, 0x1.139214p-2f, -0x1.b4e480p-8f,
        0x1.b3b008p-3f, 0x1.63a028p-3f, -0x1.701ef0p-5f, -0x1.4a8e60p-6f
    },
    {
        -0x1.0c314ep-2f, -0x1.48ee9cp-3f, 0x1.039e5cp-2f, -0x1.6f6510p-4f, -0x1.814080p-5f, -0x1.17d4bep-2f, -0x1.52e920p-3f, 0x1.239618p-2f,
        -0x1.9e70cap-3f, 0x1.b4f508p-3f, -0x1.250068p-2f, -0x1.dbc586p-3f
    },
    {
        -0x1.4a6f92p-3f, -0x1.817958p-5f, -0x1.502300p-9f, 0x1.1ab604p-2f, -0x1.cb1dbcp-3f, -0x1.07cd58p-4f, -0x1.1b29f4p-2f, 0x1.a82560p-4f,
        0x1.c986f0p-3f, -0x1.c62d60p-3f, -0x1.df6c8cp-4f, 0x1.435d34p-3f
    }
};

/*
 * Weight 4:
 * Name: weight4_fc2_bias
 * Shape: (24,)
 * Elements: 24
 * Dtype: float
 */
static const float weight4_fc2_bias[24] = {
    -0x1.9c050ap-3f, 0x1.7a1d40p-4f, -0x1.18b1fcp-4f, -0x1.dddcf0p-5f, -0x1.234558p-3f, 0x1.08b6e4p-3f, -0x1.05bbfcp-4f, 0x1.dd7318p-3f,
    -0x1.ff1b5cp-3f, 0x1.ae99a0p-3f, 0x1.d77670p-5f, 0x1.edcd58p-3f, 0x1.220dc8p-3f, 0x1.644c58p-4f, 0x1.184208p-2f, -0x1.6e8200p-9f,
    -0x1.0a1232p-3f, -0x1.2fa3e0p-6f, 0x1.688d80p-8f, 0x1.c860e8p-3f, -0x1.e5afc4p-4f, -0x1.916574p-3f, 0x1.2ede2cp-3f, -0x1.4ae1c4p-3f
};

/*
 * Weight 5:
 * Name: weight5_fc3_weight
 * Shape: (12, 24)
 * Elements: 288
 * Dtype: float
 */
static const float weight5_fc3_weight[12][24] = {
    {
        -0x1.23da98p-4f, -0x1.b99160p-4f, -0x1.2c0f28p-4f, 0x1.2dc538p-3f, -0x1.583754p-3f, -0x1.b88870p-5f, -0x1.6d167ap-4f, -0x1.b19938p-5f,
        0x1.7be840p-6f, 0x1.8843e0p-5f, 0x1.5f62e0p-5f, -0x1.7efdc2p-4f, 0x1.e81d08p-4f, -0x1.3ade5ep-3f, -0x1.969c2ep-3f, -0x1.55d9cep-3f,
        -0x1.54a6c0p-5f, 0x1.48c1d0p-5f, 0x1.beff70p-5f, -0x1.f5c0c0p-7f, 0x1.242938p-5f, -0x1.c10488p-5f, 0x1.56b1c8p-4f, 0x1.350100p-4f
    },
    {
        0x1.3c17c0p-3f, -0x1.bc61bcp-4f, 0x1.ae87d0p-5f, 0x1.c8c1d8p-4f, 0x1.77ce90p-3f, -0x1.ccdee8p-5f, 0x1.17d6ecp-3f, 0x1.5d3138p-3f,
        0x1.3b33ecp-3f, -0x1.d3beb2p-4f, -0x1.a1b3a6p-3f, 0x1.4f978cp-3f, 0x1.00b23cp-3f, -0x1.1312d4p-3f, 0x1.1b6578p-3f, 0x1.6713c0p-5f,
        -0x1.8b9b5cp-4f, 0x1.1f53e4p-3f, -0x1.93e2eep-4f, -0x1.a23e78p-4f, 0x1.c8d0a0p-7f, -0x1.999a7cp-3f, 0x1.3f6718p-5f, -0x1.008a0cp-3f
    },
    {
        0x1.a048e0p-4f, -0x1.298930p-3f, 0x1.54f9e0p-3f, -0x1.cf7c92p-4f, 0x1.f9e160p-4f, -0x1.42f1f4p-3f, 0x1.a58600p-9f, 0x1.21f6e8p-4f,
        0x1.3ad9acp-3f, 0x1.d63780p-6f, -0x1.f84ecap-4f, -0x1.3dcea0p-7f, -0x1.84b2e8p-5f, -0x1.3ac234p-3f, -0x1.295d58p-3f, 0x1.56b6e8p-5f,
        -0x1.7b313ep-3f, -0x1.a8b280p-7f, -0x1.d11da8p-5f, 0x1.9f59c8p-3f, -0x1.677910p-4f, -0x1.9c59b6p-3f, 0x1.6fd660p-7f, -0x1.211796p-3f
    },
    {
        -0x1.0d9b20p-4f, -0x1.5122e8p-4f, 0x1.7907d0p-4f, 0x1.499e88p-3f, -0x1.1ae618p-4f, -0x1.1191a4p-3f, 0x1.6b5590p-6f, 0x1.d178a0p-4f,
        -0x1.5d11f4p-3f, -0x1.b07b7cp-4f, -0x1.922938p-5f, 0x1.78d970p-5f, -0x1.56a9f8p-3f, -0x1.a142e2p-3f, -0x1.8760a2p-4f, 0x1.3b24a8p-3f,
        -0x1.958aa4p-3f, -0x1.c73080p-7f, -0x1.2da56ep-3f, -0x1.367900p-8f, -0x1.1f4dd0p-3f, 0x1.0273e4p-3f, 0x1.e06190p-4f, -0x1.60dab8p-5f
    },
    {
        -0x1.28c996p-3f, -0x1.0de98ep-3f, 0x1.1e17a4p-3f, 0x1.0c9520p-5f, 0x1.822510p-3f, 0x1.21b380p-4f, 0x1.1b8fb0p-5f, 0x1.43ee1cp-3f,
        -0x1.3d773ep-3f, 0x1.fad700p-4f, 0x1.edbe80p-8f, -0x1.0f9998p-3f, -0x1.7d5ac0p-8f, 0x1.4e51a0p-3f, -0x1.7a9034p-4f, 0x1.2cd2a8p-4f,
        -0x1.ecc230p-5f, -0x1.cddc50p-4f, 0x1.243870p-6f, -0x1.21aa9cp-3f, -0x1.621bc4p-3f, -0x1.ff74e0p-5f, -0x1.0fa1b0p-5f, 0x1.5d6690p-3f
    },
    {
        -0x1.a027aap-3f, 0x1.f3e400p-5f, 0x1.f2eb60p-7f, 0x1.485d40p-3f, 0x1.894b78p-3f, 0x1.1e45ecp-3f, -0x1.98dae0p-7f, 0x1.f4f840p-8f,
        0x1.0255f8p-4f, 0x1.9ab728p-3f, -0x1.e0c348p-5f, 0x1.024868p-3f, -0x1.386bf4p-4f, -0x1.42857cp-4f, 0x1.35a7e0p-4f, -0x1.636000p-3f,
        -0x1.c6f886p-4f, 0x1.c3ece0p-5f, 0x1.edb950p-5f, 0x1.3d9760p-4f, -0x1.dc30fcp-4f, -0x1.73d630p-5f, -0x1.22c710p-3f, -0x1.806e98p-3f
    },
    {
        -0x1.34d2dap-3f, 0x1.61e500p-3f, 0x1.cb0d50p-4f, 0x1.09c8e8p-4f, -0x1.5f2050p-4f, 0x1.a346a0p-5f, -0x1.785c20p-5f, 0x1.d76830p-4f,
        0x1.1ca184p-3f, 0x1.9b89f8p-3f, -0x1.7c68a0p-5f, 0x1.25e2c0p-3f, -0x1.5dad28p-5f, -0x1.3ffbc8p-4f, -0x1.6c9de8p-5f, 0x1.edc640p-4f,
        0x1.0019a0p-4f, 0x1.32e7fcp-3f, 0x1.1d05bcp-3f, 0x1.35acc8p-4f, -0x1.8dd606p-3f, 0x1.0d6ed0p-4f, 0x1.4abc00p-11f, -0x1.3d87d0p-3f
    },
    {
        -0x1.853bc4p-4f, -0x1.2fd608p-3f, -0x1.f46976p-4f, -0x1.c721b0p-4f, -0x1.67c128p-3f, 0x1.b0ba30p-6f, 0x1.1c5ef0p-5f, -0x1.8c6a20p-3f,
        0x1.0cb7f0p-5f, -0x1.92761cp-3f, 0x1.426e80p-6f, 0x1.367244p-3f, 0x1.9cfef8p-3f, -0x1.985224p-3f, 0x1.7c1390p-5f, 0x1.7ea0acp-3f,
        0x1.b1bc00p-12f, -0x1.6efca6p-4f, 0x1.842740p-7f, 0x1.fdf508p-4f, -0x1.1d68c6p-3f, 0x1.0c4490p-5f, -0x1.1099c8p-3f, -0x1.f391c0p-4f
    },
    {
        -0x1.adaf5ep-4f, -0x1.61bb08p-5f, -0x1.8482bap-3f, -0x1.c2da60p-7f, -0x1.7271d0p-6f, 0x1.9098a8p-3f, 0x1.07df10p-4f, 0x1.598b98p-3f,
        0x1.8df600p-5f, -0x1.b9ba48p-4f, 0x1.e1e908p-4f, -0x1.296a38p-3f, -0x1.456198p-3f, -0x1.216f88p-4f, 0x1.8b3000p-7f, 0x1.7a3820p-4f,
        0x1.aabc60p-5f, 0x1.3f19e0p-5f, 0x1.a3a710p-4f, 0x1.793718p-4f, -0x1.8c064ep-3f, 0x1.39d104p-3f, -0x1.9c2c3ap-3f, 0x1.9251a0p-5f
    },
    {
        0x1.2d9300p-7f, -0x1.dc2040p-7f, 0x1.cc9718p-4f, -0x1.8b3c68p-5f, 0x1.328980p-4f, -0x1.71b8e0p-6f, -0x1.705078p-5f, 0x1.f75548p-4f,
        0x1.0635f0p-4f, -0x1.08bea8p-4f, -0x1.5313a4p-3f, 0x1.196ffcp-3f, 0x1.6fe32cp-3f, 0x1.10fbd8p-3f, -0x1.339c5ep-3f, 0x1.138f80p-9f,
        0x1.910b20p-4f, -0x1.009c58p-5f, 0x1.677f40p-7f, 0x1.7dd220p-7f, 0x1.4e2390p-5f, -0x1.02cbf8p-4f, 0x1.d1b2c0p-4f, -0x1.611ffap-3f
    },
    {
        0x1.72ef28p-3f, 0x1.127180p-6f, -0x1.9471d8p-3f, -0x1.9bd596p-3f, 0x1.4e9200p-6f, 0x1.673640p-3f, 0x1.9f9880p-5f, 0x1.9051c8p-4f,
        0x1.0f41e0p-4f, 0x1.f747f8p-4f, 0x1.e65360p-6f, -0x1.b01072p-4f, 0x1.11fb50p-5f, -0x1.36e0a0p-5f, -0x1.bb7000p-7f, -0x1.8063eap-3f,
        0x1.224da8p-4f, -0x1.02fad4p-3f, -0x1.b496c0p-5f, 0x1.fda3b0p-4f, -0x1.351454p-3f, 0x1.038e38p-4f, -0x1.41c0dcp-4f, -0x1.ba8740p-4f
    },
    {
        -0x1.bf237ep-4f, -0x1.36f082p-3f, 0x1.4fa9f0p-5f, -0x1.1f13e0p-3f, 0x1.04dd40p-5f, -0x1.61ac08p-3f, -0x1.65d942p-3f, -0x1.5d37f4p-3f,
        0x1.2516e0p-7f, -0x1.f21b48p-5f, 0x1.db09a0p-6f, 0x1.0d63b0p-3f, 0x1.6e2cd0p-5f, 0x1.1a344cp-3f, 0x1.1f32d0p-3f, 0x1.d6cbd8p-4f,
        -0x1.0c79fcp-3f, 0x1.64b2d8p-5f, -0x1.253532p-3f, 0x1.074b7cp-3f, 0x1.7dbdb8p-4f, -0x1.0ab574p-3f, 0x1.0f3308p-4f, 0x1.9ec010p-4f
    }
};

/*
 * Weight 6:
 * Name: weight6_fc3_bias
 * Shape: (12,)
 * Elements: 12
 * Dtype: float
 */
static const float weight6_fc3_bias[12] = {
    -0x1.2f3038p-3f, -0x1.494022p-3f, 0x1.6cb928p-4f, -0x1.63bf3ap-3f, 0x1.70a394p-3f, -0x1.224fa0p-3f, 0x1.1f12a8p-3f, -0x1.868632p-3f,
    0x1.e342a0p-5f, -0x1.699610p-5f, -0x1.57a2e4p-3f, -0x1.328670p-3f
};

/*
 * Weight 7:
 * Name: weight7_fc4_weight
 * Shape: (4, 12)
 * Elements: 48
 * Dtype: float
 */
static const float weight7_fc4_weight[4][12] = {
    {
        0x1.9cacf0p-3f, 0x1.9c72c4p-3f, -0x1.599da0p-3f, 0x1.1c266cp-2f, 0x1.839a00p-6f, -0x1.25d632p-2f, -0x1.b862e4p-4f, -0x1.07f200p-7f,
        -0x1.ddb400p-9f, 0x1.f71d30p-3f, 0x1.d701b8p-3f, -0x1.db1528p-5f
    },
    {
        0x1.9242b4p-3f, -0x1.a4441ap-3f, -0x1.b5d466p-3f, -0x1.1da858p-2f, 0x1.066680p-5f, 0x1.ac2c20p-4f, -0x1.0be538p-3f, -0x1.d1cef0p-5f,
        -0x1.abbc50p-5f, 0x1.1cc480p-8f, -0x1.49aa64p-3f, -0x1.179fe2p-2f
    },
    {
        0x1.a2aea0p-5f, 0x1.6f46c8p-4f, -0x1.1f2a4ap-2f, 0x1.4733a8p-3f, 0x1.d727d8p-4f, 0x1.2d2f20p-5f, 0x1.c3ba88p-4f, 0x1.3e6298p-4f,
        -0x1.128526p-3f, -0x1.77c3cap-3f, -0x1.b40518p-3f, -0x1.68e0c6p-3f
    },
    {
        -0x1.942a9cp-3f, -0x1.212d9ap-2f, 0x1.742054p-3f, -0x1.52885ap-3f, 0x1.992000p-7f, -0x1.f4b140p-6f, -0x1.2b6cfcp-4f, -0x1.0fdb88p-2f,
        -0x1.047086p-2f, -0x1.ada5fcp-4f, 0x1.2c11c8p-4f, 0x1.470e60p-4f
    }
};

/*
 * Weight 8:
 * Name: weight8_fc4_bias
 * Shape: (4,)
 * Elements: 4
 * Dtype: float
 */
static const float weight8_fc4_bias[4] = {
    -0x1.45a3aep-3f, -0x1.8fd990p-4f, 0x1.4212e8p-3f, 0x1.204d6cp-2f
};

static inline float ref_scalar_f32_relu(float a) {
    return a > 0.0f ? a : 0.0f;
}

/*
 * Node 0:
 * OpType: Gemm
 * Name: /fc1/Gemm
 * Inputs: input, fc1.weight, fc1.bias
 * Outputs: /fc1/Gemm_output_0
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 *   transB: 1
 */
static inline void node0__fc1_gemm(const float input_a[restrict 1][6], const float input_b[restrict 12][6], const float input_c[restrict 12], float output[restrict 1][12]) {
    for (idx_t i = 0; i < 1; ++i) {
        for (idx_t j = 0; j < 12; ++j) {
            float acc = 0.0f;
            for (idx_t k = 0; k < 6; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[j][k];
                acc += a_val * b_val;
            }
            idx_t c_j = j;
            const float bias = input_c[c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

/*
 * Node 1:
 * OpType: Relu
 * Name: /relu1/Relu
 * Inputs: /fc1/Gemm_output_0
 * Outputs: /relu1/Relu_output_0
 * Attrs: n/a
 */
static inline void node1__relu1_relu(const float input0[restrict 1][12], float output[restrict 1][12]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 12; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

/*
 * Node 2:
 * OpType: Gemm
 * Name: /fc2/Gemm
 * Inputs: /relu1/Relu_output_0, fc2.weight, fc2.bias
 * Outputs: /fc2/Gemm_output_0
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 *   transB: 1
 */
static inline void node2__fc2_gemm(const float input_a[restrict 1][12], const float input_b[restrict 24][12], const float input_c[restrict 24], float output[restrict 1][24]) {
    for (idx_t i = 0; i < 1; ++i) {
        for (idx_t j = 0; j < 24; ++j) {
            float acc = 0.0f;
            for (idx_t k = 0; k < 12; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[j][k];
                acc += a_val * b_val;
            }
            idx_t c_j = j;
            const float bias = input_c[c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

/*
 * Node 3:
 * OpType: Relu
 * Name: /relu2/Relu
 * Inputs: /fc2/Gemm_output_0
 * Outputs: /relu2/Relu_output_0
 * Attrs: n/a
 */
static inline void node3__relu2_relu(const float input0[restrict 1][24], float output[restrict 1][24]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 24; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

/*
 * Node 4:
 * OpType: Gemm
 * Name: /fc3/Gemm
 * Inputs: /relu2/Relu_output_0, fc3.weight, fc3.bias
 * Outputs: /fc3/Gemm_output_0
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 *   transB: 1
 */
static inline void node4__fc3_gemm(const float input_a[restrict 1][24], const float input_b[restrict 12][24], const float input_c[restrict 12], float output[restrict 1][12]) {
    for (idx_t i = 0; i < 1; ++i) {
        for (idx_t j = 0; j < 12; ++j) {
            float acc = 0.0f;
            for (idx_t k = 0; k < 24; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[j][k];
                acc += a_val * b_val;
            }
            idx_t c_j = j;
            const float bias = input_c[c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

/*
 * Node 5:
 * OpType: Relu
 * Name: /relu3/Relu
 * Inputs: /fc3/Gemm_output_0
 * Outputs: /relu3/Relu_output_0
 * Attrs: n/a
 */
static inline void node5__relu3_relu(const float input0[restrict 1][12], float output[restrict 1][12]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        for (idx_t i1 = 0; i1 < 12; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

/*
 * Node 6:
 * OpType: Gemm
 * Name: /fc4/Gemm
 * Inputs: /relu3/Relu_output_0, fc4.weight, fc4.bias
 * Outputs: output
 * Attrs:
 *   alpha: 1.0
 *   beta: 1.0
 *   transB: 1
 */
static inline void node6__fc4_gemm(const float input_a[restrict 1][12], const float input_b[restrict 4][12], const float input_c[restrict 4], float output[restrict 1][4]) {
    for (idx_t i = 0; i < 1; ++i) {
        for (idx_t j = 0; j < 4; ++j) {
            float acc = 0.0f;
            for (idx_t k = 0; k < 12; ++k) {
                const float a_val = input_a[i][k];
                const float b_val = input_b[j][k];
                acc += a_val * b_val;
            }
            idx_t c_j = j;
            const float bias = input_c[c_j];
            output[i][j] = acc * 1.0f + bias * 1.0f;
        }
    }
}

void infineon_fully_connected_model(const float input[restrict 1][6], float output[restrict 1][4]) {
    float tmp0__fc1_Gemm_output_0[1][12];
    float tmp1__relu1_Relu_output_0[1][12];
    float tmp2__fc2_Gemm_output_0[1][24];
    float tmp3__relu2_Relu_output_0[1][24];
    float tmp4__fc3_Gemm_output_0[1][12];
    float tmp5__relu3_Relu_output_0[1][12];
    node0__fc1_gemm(input, weight1_fc1_weight, weight2_fc1_bias, tmp0__fc1_Gemm_output_0);
    node1__relu1_relu(tmp0__fc1_Gemm_output_0, tmp1__relu1_Relu_output_0);
    node2__fc2_gemm(tmp1__relu1_Relu_output_0, weight3_fc2_weight, weight4_fc2_bias, tmp2__fc2_Gemm_output_0);
    node3__relu2_relu(tmp2__fc2_Gemm_output_0, tmp3__relu2_Relu_output_0);
    node4__fc3_gemm(tmp3__relu2_Relu_output_0, weight5_fc3_weight, weight6_fc3_bias, tmp4__fc3_Gemm_output_0);
    node5__relu3_relu(tmp4__fc3_Gemm_output_0, tmp5__relu3_Relu_output_0);
    node6__fc4_gemm(tmp5__relu3_Relu_output_0, weight7_fc4_weight, weight8_fc4_bias, output);
}
