/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: True
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 081bbc3f0f23b7f2a992c48b0115ad8f5b67fc8c948bdf5ec88901cef8f49ae5
 * Model name: model
 * Graph name: test_identity_sequence
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 13
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=25
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: Identity
 * Name: n/a
 * Inputs: x
 * Outputs: y
 * Attrs: n/a
 */
void node0_identity(const float input_sequence[EMX_SEQUENCE_MAX_LEN][1][1][2][2], const idx_t input_sequence__count, float output_sequence[EMX_SEQUENCE_MAX_LEN][1][1][2][2], idx_t * output_sequence__count) {
    idx_t input_count = input_sequence__count;
    if (input_count > EMX_SEQUENCE_MAX_LEN) {
        input_count = EMX_SEQUENCE_MAX_LEN;
    }

    for (idx_t seq = 0; seq < input_count; ++seq) {
        for (idx_t elem = 0; elem < 1 * 1 * 2 * 2; ++elem) {
            ((float *)output_sequence[seq])[elem] = ((const float *)input_sequence[seq])[elem];
        }
    }

    *output_sequence__count = input_count;
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float x[EMX_SEQUENCE_MAX_LEN][1][1][2][2], idx_t x__count, float y[EMX_SEQUENCE_MAX_LEN][1], idx_t *y__count) {
    node0_identity(x, x__count, y, y__count);
}

static uint64_t rng_state = 0x243f6a8885a308d3ull;

static uint64_t rng_next_u64(void) {
    uint64_t x = rng_state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    rng_state = x;
    return x * 0x2545f4914f6cdd1dull;
}

static float rng_next_float(void) {
    return (float)((double)rng_next_u64() * (1.0 / 18446744073709551616.0));
}




__attribute__((weak, noinline)) void timer_start(void) {}
__attribute__((weak, noinline)) void timer_stop(void) {}


static void testbench_init_constant_input(void) {
    (void)0;
}

static int testbench_read_input_file(
const char *input_path, float x[EMX_SEQUENCE_MAX_LEN][1][1][2][2], idx_t *x__count) {
    FILE *input_file = fopen(input_path, "rb");
    if (!input_file) {
        fprintf(stderr, "Failed to open input file: %s\n", input_path);
        return 1;
    }
    {
        int32_t sequence_count = 0;
        if (fread(&sequence_count, sizeof(int32_t), 1, input_file) != 1) {
            fprintf(stderr, "Failed to read sequence count for input x\n");
            fclose(input_file);
            return 1;
        }
        if (sequence_count < 0 || sequence_count > EMX_SEQUENCE_MAX_LEN) {
            fprintf(stderr, "Invalid sequence count for input x: %d\n", (int)sequence_count);
            fclose(input_file);
            return 1;
        }
        *x__count = (idx_t)sequence_count;
    }
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            for (idx_t i2 = 0; i2 < 1; ++i2) {
                for (idx_t i3 = 0; i3 < 2; ++i3) {
                    for (idx_t i4 = 0; i4 < 2; ++i4) {
                        if (fread(&x[i0][i1][i2][i3][i4], sizeof(float), 1, input_file) != 1) {
                            fprintf(stderr, "Failed to read input x\n");
                            fclose(input_file);
                            return 1;
                        }
                    }
                }
            }
        }
    }

    fclose(input_file);
    return 0;
}

static void testbench_fill_random_input(float x[EMX_SEQUENCE_MAX_LEN][1][1][2][2], idx_t x__count) {
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            for (idx_t i2 = 0; i2 < 1; ++i2) {
                for (idx_t i3 = 0; i3 < 2; ++i3) {
                    for (idx_t i4 = 0; i4 < 2; ++i4) {
                        x[i0][i1][i2][i3][i4] = rng_next_float();
                    }
                }
            }
        }
    }
}

static void testbench_print_json(
float y[EMX_SEQUENCE_MAX_LEN][1], idx_t y__count) {
    printf("{\n  \"outputs\": {\n");
    printf("    \"y\": {\"shape\": [1], \"sequence_count\": %d, \"item_shapes\": [", (int)y__count);
    for (idx_t seq = 0; seq < y__count; ++seq) {
        if (seq) {
            printf(",");
        }
        printf("[");
        if (0) {
            printf(",");
        }
        printf("%d", 1);
        printf("]");
    }
    printf("], \"data\":\n      ");
    printf("[");
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("\"%a\"", (double)y[i0][i1]);
        }
        printf("]");
    }
    printf("]}");
    printf("\n  }\n}\n");
}

static int testbench_run(const char *input_path) {

    float x[EMX_SEQUENCE_MAX_LEN][1][1][2][2];
    idx_t x__count = 32;

    testbench_init_constant_input();
    if (input_path) {
        if (testbench_read_input_file(input_path, x, &x__count) != 0) {
            return 1;
        }
    } else {
        testbench_fill_random_input(x, x__count);
    }

    float y[EMX_SEQUENCE_MAX_LEN][1];
    idx_t y__count = 0;

    if (!model_load("model.bin")) {
        return 1;
    }

    timer_start();
    model(x, x__count, y, &y__count);
    timer_stop();

    testbench_print_json(y, y__count);
    return 0;
}

int main(int argc, char **argv) {
    const char *input_path = NULL;

    if (argc > 1) {
        input_path = argv[1];
    }

    return testbench_run(input_path);
}
