/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: True
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): abdd45bc43bc35db8af0385b050dae71641190b96c9c803a4f8d09309da1bc3b
 * Model name: model
 * Graph name: test_string_concat_utf8
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 9
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=20
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: StringConcat
 * Name: n/a
 * Inputs: x, y
 * Outputs: result
 * Attrs: n/a
 */
EMX_NODE_FN void node0_stringconcat(const char input0[2][EMX_STRING_MAX_LEN], const char input1[2][EMX_STRING_MAX_LEN], char output[2][EMX_STRING_MAX_LEN]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        const char *src0 = input0[i0];
        const char *src1 = input1[i0];
        char *dst = output[i0];
        strncpy(dst, src0, EMX_STRING_MAX_LEN - 1);
        dst[EMX_STRING_MAX_LEN - 1] = '\0';
        strncat(dst, src1, EMX_STRING_MAX_LEN - 1 - strlen(dst));
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const char x[restrict 2][EMX_STRING_MAX_LEN], const char y[restrict 2][EMX_STRING_MAX_LEN], char result[restrict 2][EMX_STRING_MAX_LEN]) {
    node0_stringconcat(x, y, result);
}





static const char x_testbench_data[2][EMX_STRING_MAX_LEN] = {
    "\xE7\x9A\x84", "\xE4\xB8\xAD"
};
static const char y_testbench_data[2][EMX_STRING_MAX_LEN] = {
    "\xE7\x9A\x84", "\xE4\xB8\xAD"
};

__attribute__((weak, noinline)) void timer_start(void) {}
__attribute__((weak, noinline)) void timer_stop(void) {}


static void testbench_init_constant_input(char x[2][EMX_STRING_MAX_LEN], char y[2][EMX_STRING_MAX_LEN]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        memcpy(x[i0], x_testbench_data[i0], EMX_STRING_MAX_LEN * sizeof(char));
    }
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        memcpy(y[i0], y_testbench_data[i0], EMX_STRING_MAX_LEN * sizeof(char));
    }
}

static int testbench_read_input_file(
const char *input_path) {
    (void)input_path;
    return 0;
}

static void testbench_fill_random_input(void) {
    (void)0;
}

static void testbench_print_json(
char result[2][EMX_STRING_MAX_LEN]) {
    printf("{\n  \"outputs\": {\n");
    printf("    \"result\": {\"shape\": [2], \"data\":\n      ");
    printf("[");
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("\"%s\"", result[i0]);
    }
    printf("]}");
    printf("\n  }\n}\n");
}

static int testbench_run(const char *input_path) {

    char x[2][EMX_STRING_MAX_LEN];
    char y[2][EMX_STRING_MAX_LEN];

    testbench_init_constant_input(x, y);
    if (input_path) {
        if (testbench_read_input_file(input_path) != 0) {
            return 1;
        }
    } else {
        testbench_fill_random_input();
    }

    char result[2][EMX_STRING_MAX_LEN];

    if (!model_load("model.bin")) {
        return 1;
    }

    timer_start();
    model(x, y, result);
    timer_stop();

    testbench_print_json(result);
    return 0;
}

int main(int argc, char **argv) {
    const char *input_path = NULL;

    if (argc > 1) {
        input_path = argv[1];
    }

    return testbench_run(input_path);
}
