/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: True
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 3847883f7de12d6a1fe9f10587f85a3fccabc54621ef0d5378f93ce97149ac5b
 * Model name: model
 * Graph name: test_sequence_map_identity_1_sequence
 * Inputs: 1 Outputs: 1 Nodes: 3 Initializers: 1
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=17
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const bool weight1_sequencemap_0_cond[1];

/*
 * Weight 1:
 * Name: weight1_sequencemap_0_cond
 * Shape: []
 * Elements: 1
 * Dtype: bool
 */
const EMX_UNUSED bool weight1_sequencemap_0_cond[1] = {
    true
};

/*
 * Node 0:
 * OpType: SequenceLength
 * Name: SequenceMap_0_length
 * Inputs: x
 * Outputs: SequenceMap_0_trip_count
 * Attrs: n/a
 */
void node0_sequencemap_0_length(const float input_sequence[EMX_SEQUENCE_MAX_LEN][10], const idx_t input_sequence__count, int64_t output[1]) {
    (void)input_sequence;
    idx_t input_count = input_sequence__count;
    if (input_count < 0) {
        input_count = 0;
    }
    if (input_count > EMX_SEQUENCE_MAX_LEN) {
        input_count = EMX_SEQUENCE_MAX_LEN;
    }
    output[0] = (int64_t)input_count;
}

/*
 * Node 1:
 * OpType: Loop
 * Name: SequenceMap_0_loop
 * Inputs: SequenceMap_0_trip_count, SequenceMap_0_cond, SequenceMap_0_state_0
 * Outputs: y
 * Attrs:
 *   body: GraphProto('SequenceMap_0_body', input=<3 inputs>, output=<2 outputs>, node=<4 nodes>, value_info=<3 value_info>)
 */
void node1_sequencemap_0_loop(const int64_t trip_count[1], const bool cond[1], const float input_sequence_0[EMX_SEQUENCE_MAX_LEN][10], const idx_t input_sequence_0__count, float output_sequence_0[EMX_SEQUENCE_MAX_LEN][10], idx_t * output_sequence_0__count, idx_t y__dim_0[EMX_SEQUENCE_MAX_LEN]) {
    const int64_t trip_raw = (int64_t)trip_count[0];
    const bool enabled = cond[0];
    int64_t iter_limit = (enabled && trip_raw > 0) ? trip_raw : 0;
    if (iter_limit > (int64_t)input_sequence_0__count) iter_limit = (int64_t)input_sequence_0__count;
    if (iter_limit > (int64_t)EMX_SEQUENCE_MAX_LEN) iter_limit = (int64_t)EMX_SEQUENCE_MAX_LEN;
    for (int64_t i = 0; i < iter_limit; ++i) {
        y__dim_0[(idx_t)i] = x__dim_0[(idx_t)i];
        for (idx_t e = 0; e < 10; ++e) { output_sequence_0[(idx_t)i][e] = input_sequence_0[(idx_t)i][e]; }
    }
    *output_sequence_0__count = (idx_t)iter_limit;
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float x[EMX_SEQUENCE_MAX_LEN][10], idx_t x__count, float y[EMX_SEQUENCE_MAX_LEN][10], idx_t *y__count, idx_t y__dim_0[EMX_SEQUENCE_MAX_LEN]) {
    int64_t tmp0_SequenceMap_0_trip_count[1];
    node0_sequencemap_0_length(x, x__count, tmp0_SequenceMap_0_trip_count);
    node1_sequencemap_0_loop(tmp0_SequenceMap_0_trip_count, weight1_sequencemap_0_cond, x, x__count, y, y__count, y__dim_0);
}

static uint64_t rng_state = 0x243f6a8885a308d3ull;

static uint64_t rng_next_u64(void) {
    uint64_t x = rng_state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    rng_state = x;
    return x * 0x2545f4914f6cdd1dull;
}

static float rng_next_float(void) {
    return (float)((double)rng_next_u64() * (1.0 / 18446744073709551616.0));
}




__attribute__((weak, noinline)) void timer_start(void) {}
__attribute__((weak, noinline)) void timer_stop(void) {}


static void testbench_init_constant_input(void) {
    (void)0;
}

static int testbench_read_input_file(
const char *input_path, float x[EMX_SEQUENCE_MAX_LEN][10], idx_t *x__count) {
    FILE *input_file = fopen(input_path, "rb");
    if (!input_file) {
        fprintf(stderr, "Failed to open input file: %s\n", input_path);
        return 1;
    }
    {
        int32_t sequence_count = 0;
        if (fread(&sequence_count, sizeof(int32_t), 1, input_file) != 1) {
            fprintf(stderr, "Failed to read sequence count for input x\n");
            fclose(input_file);
            return 1;
        }
        if (sequence_count < 0 || sequence_count > EMX_SEQUENCE_MAX_LEN) {
            fprintf(stderr, "Invalid sequence count for input x: %d\n", (int)sequence_count);
            fclose(input_file);
            return 1;
        }
        *x__count = (idx_t)sequence_count;
    }
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        for (idx_t i1 = 0; i1 < 10; ++i1) {
            if (fread(&x[i0][i1], sizeof(float), 1, input_file) != 1) {
                fprintf(stderr, "Failed to read input x\n");
                fclose(input_file);
                return 1;
            }
        }
    }

    fclose(input_file);
    return 0;
}

static void testbench_fill_random_input(float x[EMX_SEQUENCE_MAX_LEN][10], idx_t x__count) {
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        for (idx_t i1 = 0; i1 < 10; ++i1) {
            x[i0][i1] = rng_next_float();
        }
    }
}

static void testbench_print_json(
float y[EMX_SEQUENCE_MAX_LEN][10], idx_t y__count, idx_t y__dim_0[EMX_SEQUENCE_MAX_LEN]) {
    printf("{\n  \"outputs\": {\n");
    printf("    \"y\": {\"shape\": [10], \"sequence_count\": %d, \"item_shapes\": [", (int)y__count);
    for (idx_t seq = 0; seq < y__count; ++seq) {
        if (seq) {
            printf(",");
        }
        printf("[");
        if (0) {
            printf(",");
        }
        printf("%d", (int)y__dim_0[seq]);
        printf("]");
    }
    printf("], \"data\":\n      ");
    printf("[");
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 10; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("\"%a\"", (double)y[i0][i1]);
        }
        printf("]");
    }
    printf("]}");
    printf("\n  }\n}\n");
}

static int testbench_run(const char *input_path) {

    static float x[EMX_SEQUENCE_MAX_LEN][10];
    idx_t x__count = 32;

    testbench_init_constant_input();
    if (input_path) {
        if (testbench_read_input_file(input_path, x, &x__count) != 0) {
            return 1;
        }
    } else {
        testbench_fill_random_input(x, x__count);
    }

    static float y[EMX_SEQUENCE_MAX_LEN][10];
    idx_t y__count = 0;
    idx_t y__dim_0[EMX_SEQUENCE_MAX_LEN] = {0};

    if (!model_load("model.bin")) {
        return 1;
    }

    timer_start();
    model(x, x__count, y, &y__count, y__dim_0);
    timer_stop();

    testbench_print_json(y, y__count, y__dim_0);
    return 0;
}

int main(int argc, char **argv) {
    const char *input_path = NULL;

    if (argc > 1) {
        input_path = argv[1];
    }

    return testbench_run(input_path);
}
