/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: True
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 75c973ef57f069bc638b0cfb6593e9677111aa329409fc6cf4c9b04b9a3e4b42
 * Model name: model
 * Graph name: test_sequence_insert_at_back
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 6
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=11
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: SequenceInsert
 * Name: n/a
 * Inputs: sequence, tensor
 * Outputs: output_sequence
 * Attrs: n/a
 */
void node0_sequenceinsert(const int64_t input_sequence[EMX_SEQUENCE_MAX_LEN][3], const idx_t input_sequence__count, const int64_t tensor[3], int64_t output_sequence[EMX_SEQUENCE_MAX_LEN][3], idx_t * output_sequence__count) {
    idx_t input_count = input_sequence__count;
    if (input_count >= EMX_SEQUENCE_MAX_LEN) {
        input_count = EMX_SEQUENCE_MAX_LEN - 1;
    }
    idx_t insert_index = input_count;

    for (idx_t seq = 0; seq < insert_index; ++seq) {
        for (idx_t elem = 0; elem < 3; ++elem) {
            ((int64_t *)output_sequence[seq])[elem] = ((const int64_t *)input_sequence[seq])[elem];
        }
    }
    for (idx_t elem = 0; elem < 3; ++elem) {
        ((int64_t *)output_sequence[insert_index])[elem] = ((const int64_t *)tensor)[elem];
    }
    for (idx_t seq = insert_index; seq < input_count; ++seq) {
        for (idx_t elem = 0; elem < 3; ++elem) {
            ((int64_t *)output_sequence[seq + 1])[elem] = ((const int64_t *)input_sequence[seq])[elem];
        }
    }

    *output_sequence__count = input_count + 1;
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const int64_t sequence[EMX_SEQUENCE_MAX_LEN][3], idx_t sequence__count, const int64_t tensor[restrict 3], int64_t output_sequence[EMX_SEQUENCE_MAX_LEN][3], idx_t *output_sequence__count) {
    node0_sequenceinsert(sequence, sequence__count, tensor, output_sequence, output_sequence__count);
}





static const int64_t sequence_testbench_data[] = {
    1LL,    2LL,    3LL,    4LL,    5LL,    6LL,    7LL,    0LL,    8LL,    9LL,    0LL,    0LL};
static const int64_t tensor_testbench_data[] = {
    10LL,    11LL,    12LL};

__attribute__((weak, noinline)) void timer_start(void) {}
__attribute__((weak, noinline)) void timer_stop(void) {}


static void testbench_init_constant_input(int64_t sequence[EMX_SEQUENCE_MAX_LEN][3], int64_t tensor[3]) {
    for (idx_t i0 = 0; i0 < 3; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            sequence[i0][i1] = sequence_testbench_data[(i0 * 3 + i1)];
        }
    }
    for (idx_t i0 = 0; i0 < 3; ++i0) {
        tensor[i0] = tensor_testbench_data[i0];
    }
}

static int testbench_read_input_file(
const char *input_path) {
    (void)input_path;
    return 0;
}

static void testbench_fill_random_input(void) {
    (void)0;
}

static void testbench_print_json(
int64_t sequence[EMX_SEQUENCE_MAX_LEN][3],
int64_t tensor[3],
int64_t output_sequence[EMX_SEQUENCE_MAX_LEN][3], idx_t output_sequence__count) {
    printf("{\n  \"inputs\": {\n");
    printf("    \"sequence\": {\"shape\": [3], \"data\":\n      ");
    printf("[");
    for (idx_t i0 = 0; i0 < 3; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("%lld", (long long)sequence[i0][i1]);
        }
        printf("]");
    }
    printf("]}");
    printf(",\n");
    printf("    \"tensor\": {\"shape\": [3], \"data\":\n      ");
    printf("[");
    for (idx_t i0 = 0; i0 < 3; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("%lld", (long long)tensor[i0]);
    }
    printf("]}");

    printf("\n  },\n  \"outputs\": {\n");
    printf("    \"output_sequence\": {\"shape\": [3], \"sequence_count\": %d, \"data\":\n      ", (int)output_sequence__count);
    printf("[");
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("%lld", (long long)output_sequence[i0][i1]);
        }
        printf("]");
    }
    printf("]}");
    printf("\n  }\n}\n");
}

static int testbench_run(const char *input_path) {

    int64_t sequence[EMX_SEQUENCE_MAX_LEN][3];
    idx_t sequence__count = 3;
    int64_t tensor[3];

    testbench_init_constant_input(sequence, tensor);
    if (input_path) {
        if (testbench_read_input_file(input_path) != 0) {
            return 1;
        }
    } else {
        testbench_fill_random_input();
    }

    int64_t output_sequence[EMX_SEQUENCE_MAX_LEN][3];
    idx_t output_sequence__count = 0;

    if (!model_load("model.bin")) {
        return 1;
    }

    timer_start();
    model(sequence, sequence__count, tensor, output_sequence, &output_sequence__count);
    timer_stop();

    testbench_print_json(sequence, tensor, output_sequence, output_sequence__count);
    return 0;
}

int main(int argc, char **argv) {
    const char *input_path = NULL;

    if (argc > 1) {
        input_path = argv[1];
    }

    return testbench_run(input_path);
}
