/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: True
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 753fe39fe023477a03a783d421ae4084b5868016be007666327db564697bf2ec
 * Model name: model
 * Graph name: test_reshape_allowzero_reordered
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 13
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=25
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: Reshape
 * Name: n/a
 * Inputs: data, shape
 * Outputs: reshaped
 * Attrs:
 *   allowzero: 1
 */
EMX_NODE_FN void node0_reshape(const float input0[1][3][4], float output[3][4][1]) {
    const float *input0_data = (const float *)input0;
    for (idx_t i0 = 0; i0 < 3; ++i0) {
        for (idx_t i1 = 0; i1 < 4; ++i1) {
            for (idx_t i2 = 0; i2 < 0; ++i2) {
                output[i0][i1][i2] = input0_data[((i0 * 4 + i1) * 0 + i2)];
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float data[restrict 1][3][4], const int64_t shape[restrict 3], float reshaped[restrict 3][4][1]) {
    node0_reshape(data, reshaped);
}





static const float data_testbench_data[] = {
    {
        {
            0.0f, 0.0f, 0.0f, 0.0f
        },
        {
            0.0f, 0.0f, 0.0f, 0.0f
        },
        {
            0.0f, 0.0f, 0.0f, 0.0f
        }
    }
};
static const int64_t shape_testbench_data[] = {
    3LL, 4LL, 0LL
};

__attribute__((weak, noinline)) void timer_start(void) {}
__attribute__((weak, noinline)) void timer_stop(void) {}


static void testbench_init_constant_input(float data[1][3][4], int64_t shape[3]) {
    for (idx_t i0 = 0; i0 < 0; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                data[i0][i1][i2] = data_testbench_data[((i0 * 3 + i1) * 4 + i2)];
            }
        }
    }
    for (idx_t i0 = 0; i0 < 3; ++i0) {
        shape[i0] = shape_testbench_data[i0];
    }
}

static int testbench_read_input_file(
const char *input_path) {
    (void)input_path;
    return 0;
}

static void testbench_fill_random_input(void) {
    (void)0;
}

static void testbench_print_json(
float reshaped[3][4][1]) {
    printf("{\n  \"outputs\": {\n");
    printf("    \"reshaped\": {\"shape\": [3,4,0], \"data\":\n      ");
    printf("[");
    for (idx_t i0 = 0; i0 < 3; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 4; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("[");
            for (idx_t i2 = 0; i2 < 0; ++i2) {
                if (i2) {
                    printf(",");
                }
                printf("\"%a\"", (double)reshaped[i0][i1][i2]);
            }
            printf("]");
        }
        printf("]");
    }
    printf("]}");
    printf("\n  }\n}\n");
}

static int testbench_run(const char *input_path) {

    float data[1][3][4];
    int64_t shape[3];

    testbench_init_constant_input(data, shape);
    if (input_path) {
        if (testbench_read_input_file(input_path) != 0) {
            return 1;
        }
    } else {
        testbench_fill_random_input();
    }

    float reshaped[3][4][1];

    if (!model_load("model.bin")) {
        return 1;
    }

    timer_start();
    model(data, shape, reshaped);
    timer_stop();

    testbench_print_json(reshaped);
    return 0;
}

int main(int argc, char **argv) {
    const char *input_path = NULL;

    if (argc > 1) {
        input_path = argv[1];
    }

    return testbench_run(input_path);
}
