/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): bbea43b4d5fedab13f073a55c166560d873223af6f853074c6383b007a44c357
 * Model name: model
 * Graph name: add_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

static inline float ref_scalar_f32_add(float a, float b) {
    return a + b;
}

/*
 * Node 0:
 * OpType: Add
 * Name: n/a
 * Inputs: a, b
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_add(const float input0[2][3][4], const float input1[2][3][4], float output[2][3][4]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            for (idx_t i2 = 0; i2 < 4; ++i2) {
                output[i0][i1][i2] = ref_scalar_f32_add(input0[i0][i1][i2], input1[i0][i1][i2]);
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float a[restrict 2][3][4], const float b[restrict 2][3][4], float out[restrict 2][3][4]) {
    node0_add(a, b, out);
}
