/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): c9fb9a6973ba3966976688439dabfde70582fbe9320752bef1d0f4b321b0c8d7
 * Model name: model
 * Graph name: cast_f32_to_f8e4m3fn
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 10
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=25
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif
typedef uint8_t emx_float8e4m3fn_t;

static inline emx_float8e4m3fn_t ref_scalar_f8e4m3fn_from_f32(float v) {
    if (v != v) return 0x7Fu;
    uint8_t s = signbit(v) ? 0x80u : 0u;
    float a = fabsf(v);
    if (a == 0.0f) return s;
    if (a > 448.0f) return s | 0x7Eu;
    int e; float f = frexpf(a, &e); e--; f *= 2.0f;
    int be = e + 7;
    if (be >= 1) {
        int m = (int)rintf((f - 1.0f) * 8.0f);
        if (m >= 8) { m = 0; be++; }
        if (be > 15 || (be == 15 && m >= 7)) return s | 0x7Eu;
        return s | (uint8_t)((be << 3) | m);
    }
    int m = (int)rintf(ldexpf(a, 9));
    if (m >= 8) return s | (1u << 3);
    if (m <= 0) return s;
    return s | (uint8_t)m;
}

/*
 * Node 0:
 * OpType: Cast
 * Name: n/a
 * Inputs: x
 * Outputs: y
 * Attrs:
 *   to: 17
 */
EMX_NODE_FN void node0_cast(const float input0[2][3], emx_float8e4m3fn_t output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f8e4m3fn_from_f32((float)input0[i0][i1]);
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float x[restrict 2][3], emx_float8e4m3fn_t y[restrict 2][3]) {
    node0_cast(x, y);
}
