/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 5d73cdad94836170408163ed1f9be074b094f943b4430d6ce7bc82c707004a6d
 * Model name: constant_string_model
 * Graph name: constant_string_graph
 * Inputs: 0 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif

extern const char weight1_const_out[2][EMX_STRING_MAX_LEN];

/*
 * Weight 1:
 * Name: weight1_const_out
 * Shape: (2,)
 * Elements: 2
 * Dtype: string
 */
const EMX_UNUSED char weight1_const_out[2][EMX_STRING_MAX_LEN] = {
    "hello", "world"
};

/*
 * Node 0:
 * OpType: Identity
 * Name: n/a
 * Inputs: const_out
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_identity(const char input0[2][EMX_STRING_MAX_LEN], char output[2][EMX_STRING_MAX_LEN]) {
    memcpy(output, input0, sizeof(char) * 2 * EMX_STRING_MAX_LEN);
}

_Bool constant_string_model_load(const char *path) {
    (void)path;
    return 1;
}

void constant_string_model(char out[restrict 2][EMX_STRING_MAX_LEN]) {
    node0_identity(weight1_const_out, out);
}
