/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): e1230dbe10f508bb16efa3b5338183ee4082a095cf45c7c808c443438076df23
 * Model name: dynamic_dims_model
 * Graph name: relu_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif

static inline float ref_scalar_f32_relu(float a) {
    return a > 0.0f ? a : 0.0f;
}

/*
 * Node 0:
 * OpType: Relu
 * Name: n/a
 * Inputs: x
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_relu(int N, int C, const float input0[N][C], float output[N][C]) {
    for (idx_t i0 = 0; i0 < N; ++i0) {
        for (idx_t i1 = 0; i1 < C; ++i1) {
            output[i0][i1] = ref_scalar_f32_relu(input0[i0][i1]);
        }
    }
}

_Bool dynamic_dims_model_load(const char *path) {
    (void)path;
    return 1;
}

void dynamic_dims_model(int N, int C, const float x[restrict N][C], float out[restrict N][C]) {
    node0_relu(N, C, x, out);
}
