/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): e53e5aa822a01eee398db0cc5926f3a7738911483e917232e5277b80e8012923
 * Model name: identity_string_model
 * Graph name: identity_string_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif

/*
 * Node 0:
 * OpType: Identity
 * Name: n/a
 * Inputs: x
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_identity(const char input0[2][EMX_STRING_MAX_LEN], char output[2][EMX_STRING_MAX_LEN]) {
    memcpy(output, input0, sizeof(char) * 2 * EMX_STRING_MAX_LEN);
}

_Bool identity_string_model_load(const char *path) {
    (void)path;
    return 1;
}

void identity_string_model(const char x[restrict 2][EMX_STRING_MAX_LEN], char out[restrict 2][EMX_STRING_MAX_LEN]) {
    node0_identity(x, out);
}
