/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 40275ccd2754253bdba39f80c89af8257e001b6981b849c9af0f43eb71d82f7c
 * Model name: loop_range_float_model
 * Graph name: test_range_float_type_positive_delta_expanded
 * Inputs: 3 Outputs: 1 Nodes: 9 Initializers: 0
 * IR version: 6
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=11
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdbool.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

static inline float ref_scalar_f32_sub(float a, float b) {
    return a - b;
}

static inline float ref_scalar_f32_div(float a, float b) {
    return a / b;
}

static inline float ref_scalar_f32_ceil(float a) {
    return ceilf(a);
}

static inline float ref_scalar_f32_relu(float a) {
    return a > 0.0f ? a : 0.0f;
}

/*
 * Node 0:
 * OpType: Sub
 * Name: n/a
 * Inputs: limit, start
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_sub_result
 * Attrs: n/a
 */
static inline void node0_sub(const float input0[1], const float input1[1], float output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = ref_scalar_f32_sub(input0[0], input1[0]);
    }
}

/*
 * Node 1:
 * OpType: Cast
 * Name: n/a
 * Inputs: Range_test_range_float_type_positive_delta_expanded_function_sub_result
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_sub_result_casted
 * Attrs:
 *   to: 1
 */
static inline void node1_cast(const float input0[1], float output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = (float)input0[i0];
    }
}

/*
 * Node 2:
 * OpType: Cast
 * Name: n/a
 * Inputs: delta
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_delta_casted
 * Attrs:
 *   to: 1
 */
static inline void node2_cast(const float input0[1], float output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = (float)input0[i0];
    }
}

/*
 * Node 3:
 * OpType: Div
 * Name: n/a
 * Inputs: Range_test_range_float_type_positive_delta_expanded_function_sub_result_casted, Range_test_range_float_type_positive_delta_expanded_function_delta_casted
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_div_result
 * Attrs: n/a
 */
static inline void node3_div(const float input0[1], const float input1[1], float output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = ref_scalar_f32_div(input0[0], input1[0]);
    }
}

/*
 * Node 4:
 * OpType: Ceil
 * Name: n/a
 * Inputs: Range_test_range_float_type_positive_delta_expanded_function_div_result
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_ceil_result
 * Attrs: n/a
 */
static inline void node4_ceil(const float input0[1], float output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = ref_scalar_f32_ceil(input0[i0]);
    }
}

/*
 * Node 5:
 * OpType: Relu
 * Name: n/a
 * Inputs: Range_test_range_float_type_positive_delta_expanded_function_ceil_result
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu
 * Attrs: n/a
 */
static inline void node5_relu(const float input0[1], float output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = ref_scalar_f32_relu(input0[i0]);
    }
}

/*
 * Node 6:
 * OpType: Cast
 * Name: n/a
 * Inputs: Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_int
 * Attrs:
 *   to: 7
 */
static inline void node6_cast(const float input0[1], int64_t output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = (int64_t)input0[i0];
    }
}

/*
 * Node 7:
 * OpType: Cast
 * Name: n/a
 * Inputs: Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_bool
 * Attrs:
 *   to: 9
 */
static inline void node7_cast(const float input0[1], bool output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = (bool)input0[i0];
    }
}

/*
 * Node 8:
 * OpType: Loop
 * Name: n/a
 * Inputs: Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_int, Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_bool, start
 * Outputs: Range_test_range_float_type_positive_delta_expanded_function_variadic_output, output
 * Attrs:
 *   body: GraphProto('loop_body_attribute', input=<3 inputs>, output=<3 outputs>, node=<3 nodes>, value_info=<3 value_info>)
 */
static inline void node8_loop(const int64_t trip_count[1], const bool cond[1], const float start[1], const float delta[1], float final[1], float output[2]) {
    const int64_t trip = (int64_t)trip_count[0];
    const bool enabled = cond[0];
    float current = start[0];
    if (!enabled || trip <= 0) {
        final[0] = current;
        return;
    }
    const float delta_value = delta[0];
    for (int64_t idx = 0; idx < trip; ++idx) {
        output[idx] = current;
        current = current + delta_value;
    }
    final[0] = current;
}

_Bool loop_range_float_model_load(const char *path) {
    (void)path;
    return 1;
}

void loop_range_float_model(const float start[restrict 1], const float limit[restrict 1], const float delta[restrict 1], float output[restrict 2]) {
    float tmp0_Range_test_range_float_type_positive_delta_expanded_function_sub_result[1];
    float tmp1_Range_test_range_float_type_positive_delta_expanded_function_sub_result_casted[1];
    float tmp2_Range_test_range_float_type_positive_delta_expanded_function_delta_casted[1];
    float tmp3_Range_test_range_float_type_positive_delta_expanded_function_div_result[1];
    float tmp4_Range_test_range_float_type_positive_delta_expanded_function_ceil_result[1];
    float tmp5_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu[1];
    int64_t tmp6_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_int[1];
    bool tmp7_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_bool[1];
    float tmp8_Range_test_range_float_type_positive_delta_expanded_function_variadic_output[1];
    node0_sub(limit, start, tmp0_Range_test_range_float_type_positive_delta_expanded_function_sub_result);
    node1_cast(tmp0_Range_test_range_float_type_positive_delta_expanded_function_sub_result, tmp1_Range_test_range_float_type_positive_delta_expanded_function_sub_result_casted);
    node2_cast(delta, tmp2_Range_test_range_float_type_positive_delta_expanded_function_delta_casted);
    node3_div(tmp1_Range_test_range_float_type_positive_delta_expanded_function_sub_result_casted, tmp2_Range_test_range_float_type_positive_delta_expanded_function_delta_casted, tmp3_Range_test_range_float_type_positive_delta_expanded_function_div_result);
    node4_ceil(tmp3_Range_test_range_float_type_positive_delta_expanded_function_div_result, tmp4_Range_test_range_float_type_positive_delta_expanded_function_ceil_result);
    node5_relu(tmp4_Range_test_range_float_type_positive_delta_expanded_function_ceil_result, tmp5_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu);
    node6_cast(tmp5_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu, tmp6_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_int);
    node7_cast(tmp5_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu, tmp7_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_bool);
    node8_loop(tmp6_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_int, tmp7_Range_test_range_float_type_positive_delta_expanded_function_ceil_result_relu_bool, start, delta, tmp8_Range_test_range_float_type_positive_delta_expanded_function_variadic_output, output);
}
