/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 9e433994b5ef0942dd462e00c4c65a980e25139b349b6221872d5830fb2fdae2
 * Model name: model
 * Graph name: mul_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

static inline float ref_scalar_f32_mul(float a, float b) {
    return a * b;
}

/*
 * Node 0:
 * OpType: Mul
 * Name: n/a
 * Inputs: a, b
 * Outputs: out
 * Attrs: n/a
 */
EMX_NODE_FN void node0_mul(const float input0[2][3], const float input1[2][3], float output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_mul(input0[i0][i1], input1[i0][i1]);
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float a[restrict 2][3], const float b[restrict 2][3], float out[restrict 2][3]) {
    node0_mul(a, b, out);
}
