// Generated by emx-onnx2c (MVP)
#include <stddef.h>

void model_op0(const float a[2][3], const float b[2][3], float tmp0[2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            tmp0[i0][i1] = a[i0][i1] * b[i0][i1];
        }
    }
}

void model_op1(const float tmp0[2][3], const float c[2][3], float tmp1[2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            tmp1[i0][i1] = tmp0[i0][i1] + c[i0][i1];
        }
    }
}

void model_op2(const float tmp1[2][3], float out[2][3]) {
    for (size_t i0 = 0; i0 < 2; ++i0) {
        for (size_t i1 = 0; i1 < 3; ++i1) {
            out[i0][i1] = tmp1[i0][i1] > 0.0f ? tmp1[i0][i1] : 0.0f;
        }
    }
}

void model(const float a[2][3], const float b[2][3], const float c[2][3], float out[2][3]) {
    float tmp0[2][3];
    float tmp1[2][3];
    model_op0(a, b, tmp0);
    model_op1(tmp0, c, tmp1);
    model_op2(tmp1, out);
}
