/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 37d6abd6fd7c648e73d1787fab27edac5450f63bd919162f152495b27c4afc6a
 * Model name: model
 * Graph name: affine_grid_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 9
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=20
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: AffineGrid
 * Name: n/a
 * Inputs: theta, size
 * Outputs: grid
 * Attrs:
 *   align_corners: 0
 */
EMX_NODE_FN void node0_affinegrid(const float theta[2][2][3], const int64_t size[4], float grid[2][5][6][2]) {
    for (idx_t n = 0; n < 2; ++n) {
        for (idx_t h = 0; h < 5; ++h) {
            for (idx_t w = 0; w < 6; ++w) {
                const float y_coord = (float)-1 + ((float)2 * h + (float)1) / (float)5;
                const float x_coord = (float)-1 + ((float)2 * w + (float)1) / (float)6;
                grid[n][h][w][0] = theta[n][0][0] * x_coord + theta[n][0][1] * y_coord + theta[n][0][2];
                grid[n][h][w][1] = theta[n][1][0] * x_coord + theta[n][1][1] * y_coord + theta[n][1][2];
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float theta[restrict 2][2][3], const int64_t size[restrict 4], float grid[restrict 2][5][6][2]) {
    node0_affinegrid(theta, size, grid);
}
