/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 74802e4b39801d33a3e74017999a8a2804f28f316ee52f3d14b9a53dbd4c0436
 * Model name: model
 * Graph name: binarizer_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13, ai.onnx.ml=1
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

static inline float ref_scalar_f32_binarizer__0p25(float a) {
    const float threshold = 0.25f;
    return a > threshold ? 1.0f : 0.0f;
}

/*
 * Node 0:
 * OpType: Binarizer
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   threshold: 0.25
 */
EMX_NODE_FN void node0_binarizer(const float input0[2][3], float output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = ref_scalar_f32_binarizer__0p25(input0[i0][i1]);
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 2][3], float out[restrict 2][3]) {
    node0_binarizer(in0, out);
}
