/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 322340c74141029528d668a2025bb60c505d501d3ffdea7315f7b96d80c420ad
 * Model name: model
 * Graph name: cumsum_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=14
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const int64_t weight1_axis[1];

/*
 * Weight 1:
 * Name: weight1_axis
 * Shape: []
 * Elements: 1
 * Dtype: int64
 */
const EMX_UNUSED int64_t weight1_axis[1] = {
    1LL
};

/*
 * Node 0:
 * OpType: CumSum
 * Name: n/a
 * Inputs: input, axis
 * Outputs: output
 * Attrs:
 *   exclusive: 0
 *   reverse: 0
 */
EMX_NODE_FN void node0_cumsum(const float input0[2][3], float output[2][3]) {
    int axis = 1;
    if (axis < 0) {
        axis += 2;
    }
    if (axis < 0 || axis >= 2) {
        return;
    }
    switch (axis) {
        case 0:
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            float acc = (float)0;
            for (idx_t i0 = 0; i0 < 2; ++i0) {
                acc += input0[i0][i1];
                output[i0][i1] = acc;
            }
        }
        break;
        case 1:
        for (idx_t i0 = 0; i0 < 2; ++i0) {
            float acc = (float)0;
            for (idx_t i1 = 0; i1 < 3; ++i1) {
                acc += input0[i0][i1];
                output[i0][i1] = acc;
            }
        }
        break;
        default:
        return;
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 2][3], float output[restrict 2][3]) {
    node0_cumsum(input, output);
}
