/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): d6f0bb05d74860e6d2f211704a49ffa70dcc5a2c4b1ca28b355b50f0c85e9c25
 * Model name: model
 * Graph name: causal_conv_with_state_graph
 * Inputs: 2 Outputs: 2 Nodes: 1 Initializers: 2
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: com.microsoft=1
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const float weight1_weight[2][1][3];
extern const float weight2_bias[2];

/*
 * Weight 1:
 * Name: weight1_weight
 * Shape: (2, 1, 3)
 * Elements: 6
 * Dtype: float
 */
const EMX_UNUSED float weight1_weight[2][1][3] = {
    {
        {
            0x0.0p+0f, 0x1.555556p-2f, 0x1.555556p-1f
        }
    },
    {
        {
            0x1.000000p+0f, 0x1.555556p+0f, 0x1.aaaaaap+0f
        }
    }
};

/*
 * Weight 2:
 * Name: weight2_bias
 * Shape: (2,)
 * Elements: 2
 * Dtype: float
 */
const EMX_UNUSED float weight2_bias[2] = {
    -0x1.000000p-2f, 0x1.000000p-2f
};

static inline float ref_scalar_f32_swish(float a) {
    const float alpha = 1.0f;
    return a / (1.0f + expf(-alpha * a));
}

/*
 * Node 0:
 * OpType: CausalConvWithState
 * Name: n/a
 * Inputs: input, weight, bias, past_state
 * Outputs: output, present_state
 * Attrs:
 *   activation: silu
 *   ndim: 1
 */
EMX_NODE_FN void node0_causalconvwithstate(const float input0[1][2][4], const float weights[2][1][3], const float bias[2], const float past_state[1][2][2], float output[1][2][4], float present_state[1][2][2]) {
    for (idx_t b = 0; b < 1; ++b) {
        for (idx_t c = 0; c < 2; ++c) {
            for (idx_t out_idx = 0; out_idx < 4; ++out_idx) {
                float acc = (float)bias[c];
                for (idx_t k = 0; k < 3; ++k) {
                    const idx_t window_idx = out_idx + k;
                    float sample = 0.0f;
                    if (window_idx < 2) {
                        sample = (float)past_state[b][c][window_idx];
                    } else {
                        sample = (float)input0[b][c][window_idx - 2];
                    }
                    acc += sample * (float)weights[c][0][k];
                }
                acc = ref_scalar_f32_swish(acc);
                output[b][c][out_idx] = (float)acc;
            }
            for (idx_t state_idx = 0; state_idx < 2; ++state_idx) {
                const idx_t concat_idx = 4 + state_idx;
                float sample = 0.0f;
                if (concat_idx < 2) {
                    sample = past_state[b][c][concat_idx];
                } else {
                    sample = input0[b][c][concat_idx - 2];
                }
                present_state[b][c][state_idx] = sample;
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 1][2][4], const float past_state[restrict 1][2][2], float output[restrict 1][2][4], float present_state[restrict 1][2][2]) {
    node0_causalconvwithstate(input, weight1_weight, weight2_bias, past_state, output, present_state);
}
