/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 64d377b84cafa5584d133ba44f9aa688b5dc41c11bbe2d15d6284b672b511f77
 * Model name: model
 * Graph name: deform_conv_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=19
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const float weight1_w[1][1][2][2];

/*
 * Weight 1:
 * Name: weight1_w
 * Shape: (1, 1, 2, 2)
 * Elements: 4
 * Dtype: float
 */
const EMX_UNUSED float weight1_w[1][1][2][2] = {
    {
        {
            {
                0x1.000000p+0f, 0x1.000000p+0f
            },
            {
                0x1.000000p+0f, 0x1.000000p+0f
            }
        }
    }
};

/*
 * Node 0:
 * OpType: DeformConv
 * Name: n/a
 * Inputs: X, W, offset
 * Outputs: Y
 * Attrs:
 *   kernel_shape: [2, 2]
 *   pads: [0, 0, 0, 0]
 */
EMX_NODE_FN void node0_deformconv(const float input0[1][1][3][3], const float weights[1][1][2][2], const float offset[1][8][2][2], float output[1][1][2][2]) {
    for (idx_t n = 0; n < 1; ++n) {
        for (idx_t g = 0; g < 1; ++g) {
            for (idx_t oc = 0; oc < 1; ++oc) {
                const idx_t oc_global = g * 1 + oc;
                for (idx_t oh = 0; oh < 2; ++oh) {
                    for (idx_t ow = 0; ow < 2; ++ow) {
                        float acc = 0.0f;
                        for (idx_t ic = 0; ic < 1; ++ic) {
                            const idx_t ic_global = g * 1 + ic;
                            const idx_t off_g = ic_global / 1;
                            for (idx_t kh = 0; kh < 2; ++kh) {
                                for (idx_t kw = 0; kw < 2; ++kw) {
                                    const idx_t off_ch_h = (off_g * 2 * 2 + kh * 2 + kw) * 2;
                                    const idx_t off_ch_w = off_ch_h + 1;
                                    const double dh = (double)offset[n][off_ch_h][oh][ow];
                                    const double dw = (double)offset[n][off_ch_w][oh][ow];
                                    const double h_coord = (double)(oh * 1 - 0 + kh * 1) + dh;
                                    const double w_coord = (double)(ow * 1 - 0 + kw * 1) + dw;
                                    const int base_h = (int)floor(h_coord);
                                    const int base_w = (int)floor(w_coord);
                                    const double frac_h = h_coord - (double)base_h;
                                    const double frac_w = w_coord - (double)base_w;
                                    double sample = 0.0;
                                    int ih0 = base_h, ih1 = base_h + 1;
                                    int iw0 = base_w, iw1 = base_w + 1;
                                    double v00 = (ih0 >= 0 && ih0 < 3 && iw0 >= 0 && iw0 < 3) ? (double)input0[n][ic_global][ih0][iw0] : 0.0;
                                    double v01 = (ih0 >= 0 && ih0 < 3 && iw1 >= 0 && iw1 < 3) ? (double)input0[n][ic_global][ih0][iw1] : 0.0;
                                    double v10 = (ih1 >= 0 && ih1 < 3 && iw0 >= 0 && iw0 < 3) ? (double)input0[n][ic_global][ih1][iw0] : 0.0;
                                    double v11 = (ih1 >= 0 && ih1 < 3 && iw1 >= 0 && iw1 < 3) ? (double)input0[n][ic_global][ih1][iw1] : 0.0;
                                    sample = (1.0 - frac_h) * (1.0 - frac_w) * v00 + (1.0 - frac_h) * frac_w * v01 + frac_h * (1.0 - frac_w) * v10 + frac_h * frac_w * v11;
                                    acc += (float)(sample * (double)weights[oc_global][ic][kh][kw]);
                                }
                            }
                        }
                        output[n][oc_global][oh][ow] = (float)acc;
                    }
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float X[restrict 1][1][3][3], const float offset[restrict 1][8][2][2], float Y[restrict 1][1][2][2]) {
    node0_deformconv(X, weight1_w, offset, Y);
}
