/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): b274fac53b86be576d3c3ba70f0eddd1425a85aace97906d4887e5d8121a4f3a
 * Model name: model
 * Graph name: group_query_attention_graph
 * Inputs: 5 Outputs: 3 Nodes: 1 Initializers: 2
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13, com.microsoft=1
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const int32_t weight1_seqlens_k[1];
extern const int32_t weight2_total_sequence_length[1];

/*
 * Weight 1:
 * Name: weight1_seqlens_k
 * Shape: (1,)
 * Elements: 1
 * Dtype: int32
 */
const EMX_UNUSED int32_t weight1_seqlens_k[1] = {
    0
};

/*
 * Weight 2:
 * Name: weight2_total_sequence_length
 * Shape: (1,)
 * Elements: 1
 * Dtype: int32
 */
const EMX_UNUSED int32_t weight2_total_sequence_length[1] = {
    4
};

/*
 * Node 0:
 * OpType: GroupQueryAttention
 * Name: n/a
 * Inputs: query, key, value, past_key, past_value, seqlens_k, total_sequence_length, , , , , 
 * Outputs: output, present_key, present_value
 * Attrs:
 *   k_quant_type: NONE
 *   kv_num_heads: 1
 *   local_window_size: -1
 *   num_heads: 2
 *   qk_output: 0
 *   smooth_softmax: -1
 *   v_quant_type: NONE
 */
EMX_NODE_FN void node0_groupqueryattention(const float query[1][1][16], const float key[1][1][8], const float value[1][1][8], const float past_key[1][1][4][8], const float past_value[1][1][4][8], const int32_t seqlens_k[1], const int32_t total_sequence_length[1], float output[1][1][16], float present_key[1][1][4][8], float present_value[1][1][4][8]) {
    const float scale = 0.353553391f;

    int max_total_seq = (int)total_sequence_length[0];
    if (max_total_seq < 1) {
        max_total_seq = 1;
    }
    if (max_total_seq > 4) {
        max_total_seq = 4;
    }

    for (int b = 0; b < 1; ++b) {
        int cur_pos = (int)seqlens_k[b];
        if (cur_pos < 0) {
            cur_pos = 0;
        }
        if (cur_pos >= max_total_seq) {
            cur_pos = max_total_seq - 1;
        }
        int total_seq = cur_pos + 1;

        for (int h = 0; h < 1; ++h) {
            for (int s = 0; s < 4; ++s) {
                for (int d = 0; d < 8; ++d) {
                    present_key[b][h][s][d] = past_key[b][h][s][d];
                }
                for (int d = 0; d < 8; ++d) {
                    present_value[b][h][s][d] = past_value[b][h][s][d];
                }
            }
        }

        for (int h = 0; h < 1; ++h) {
            for (int d = 0; d < 8; ++d) {
                present_key[b][h][cur_pos][d] = key[b][0][h * 8 + d];
            }
            for (int d = 0; d < 8; ++d) {
                present_value[b][h][cur_pos][d] = value[b][0][h * 8 + d];
            }
            for (int s = total_seq; s < 4; ++s) {
                for (int d = 0; d < 8; ++d) {
                    present_key[b][h][s][d] = 0.0f;
                }
                for (int d = 0; d < 8; ++d) {
                    present_value[b][h][s][d] = 0.0f;
                }
            }
        }

        for (int qi = 0; qi < 1; ++qi) {
            for (int qh = 0; qh < 2; ++qh) {
                int kv_head = qh / 2;

                float q[8];
                for (int d = 0; d < 8; ++d) {
                    q[d] = query[b][qi][qh * 8 + d];
                }

                float scores[4];
                float max_score = -INFINITY;
                for (int ki = 0; ki < total_seq; ++ki) {
                    float score = 0.0f;
                    for (int d = 0; d < 8; ++d) {
                        score += q[d] * present_key[b][kv_head][ki][d];
                    }
                    score *= scale;
                    scores[ki] = score;
                    if (score > max_score) {
                        max_score = score;
                    }
                }

                float sum_exp = 0.0f;
                for (int ki = 0; ki < total_seq; ++ki) {
                    scores[ki] = expf(scores[ki] - max_score);
                    sum_exp += scores[ki];
                }
                for (int ki = 0; ki < total_seq; ++ki) {
                    scores[ki] /= sum_exp;
                }

                for (int d = 0; d < 8; ++d) {
                    float acc = 0.0f;
                    for (int ki = 0; ki < total_seq; ++ki) {
                        acc += scores[ki] * present_value[b][kv_head][ki][d];
                    }
                    output[b][qi][qh * 8 + d] = acc;
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float query[restrict 1][1][16], const float key[restrict 1][1][8], const float value[restrict 1][1][8], const float past_key[restrict 1][1][4][8], const float past_value[restrict 1][1][4][8], float output[restrict 1][1][16], float present_key[restrict 1][1][4][8], float present_value[restrict 1][1][4][8]) {
    node0_groupqueryattention(query, key, value, past_key, past_value, weight1_seqlens_k, weight2_total_sequence_length, output, present_key, present_value);
}
