/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 7fdfeccef4d24a032d65129a64d44bdcd63f0e518411a671b7a6cf0fa854980b
 * Model name: model
 * Graph name: linear_attention_graph
 * Inputs: 6 Outputs: 2 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13, com.microsoft=1
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

static inline float ref_scalar_f32_exp(float a) {
    return expf(a);
}

/*
 * Node 0:
 * OpType: LinearAttention
 * Name: n/a
 * Inputs: query, key, value, past_state, decay, beta
 * Outputs: output, present_state
 * Attrs:
 *   chunk_size: 64
 *   kv_num_heads: 2
 *   q_num_heads: 4
 *   scale: 0.5
 *   update_rule: gated_delta
 */
EMX_NODE_FN void node0_linearattention(const float query[1][2][8], const float key[1][2][4], const float value[1][2][6], const float past_state[1][2][2][3], const float decay[1][2][2], const float beta[1][2][2], float output[1][2][12], float present_state[1][2][2][3]) {
    const float scale = 0.5f;
    for (int b = 0; b < 1; ++b) {
        for (int h = 0; h < 2; ++h) {
            for (int dk = 0; dk < 2; ++dk) {
                for (int dv = 0; dv < 3; ++dv) {
                    present_state[b][h][dk][dv] = past_state[b][h][dk][dv];
                }
            }
        }
    }
    for (int b = 0; b < 1; ++b) {
        for (int ti = 0; ti < 2; ++ti) {
            for (int h = 0; h < 2; ++h) {
                int k_head = h / 1;
                float decay_factor = ref_scalar_f32_exp(decay[b][ti][h]);
                for (int dk = 0; dk < 2; ++dk) {
                    for (int dv = 0; dv < 3; ++dv) {
                        present_state[b][h][dk][dv] *= decay_factor;
                    }
                }
                float residual[3];
                for (int dv = 0; dv < 3; ++dv) {
                    float prev_value = 0.0f;
                    for (int dk = 0; dk < 2; ++dk) {
                        prev_value += present_state[b][h][dk][dv] * key[b][ti][k_head * 2 + dk];
                    }
                    residual[dv] = value[b][ti][h * 3 + dv] - prev_value;
                }
                float beta_value = beta[b][ti][h];
                for (int dk = 0; dk < 2; ++dk) {
                    float key_value = key[b][ti][k_head * 2 + dk];
                    for (int dv = 0; dv < 3; ++dv) {
                        present_state[b][h][dk][dv] += beta_value * key_value * residual[dv];
                    }
                }
                for (int gh = 0; gh < 2; ++gh) {
                    int qh = h * 2 + gh;
                    for (int dv = 0; dv < 3; ++dv) {
                        float acc = 0.0f;
                        for (int dk = 0; dk < 2; ++dk) {
                            acc += query[b][ti][qh * 2 + dk] * present_state[b][h][dk][dv];
                        }
                        output[b][ti][qh * 3 + dv] = scale * acc;
                    }
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float query[restrict 1][2][8], const float key[restrict 1][2][4], const float value[restrict 1][2][6], const float past_state[restrict 1][2][2][3], const float decay[restrict 1][2][2], const float beta[restrict 1][2][2], float output[restrict 1][2][12], float present_state[restrict 1][2][2][3]) {
    node0_linearattention(query, key, value, past_state, decay, beta, output, present_state);
}
