/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 2972e3e735f93cf7cb164e5f1508eda2d6714c198f193b7cf688f41ad6f856a6
 * Model name: model
 * Graph name: matmulinteger_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 3
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=10
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const uint8_t weight1_in1[3][4];
extern const uint8_t weight2_a_zero_point[1];
extern const uint8_t weight3_b_zero_point[1];

/*
 * Weight 1:
 * Name: weight1_in1
 * Shape: (3, 4)
 * Elements: 12
 * Dtype: uint8
 */
const EMX_UNUSED uint8_t weight1_in1[3][4] = {
    {
        0, 1, 2, 3
    },
    {
        4, 5, 6, 7
    },
    {
        8, 9, 10, 11
    }
};

/*
 * Weight 2:
 * Name: weight2_a_zero_point
 * Shape: []
 * Elements: 1
 * Dtype: uint8
 */
const EMX_UNUSED uint8_t weight2_a_zero_point[1] = {
    1
};

/*
 * Weight 3:
 * Name: weight3_b_zero_point
 * Shape: []
 * Elements: 1
 * Dtype: uint8
 */
const EMX_UNUSED uint8_t weight3_b_zero_point[1] = {
    2
};

/*
 * Node 0:
 * OpType: MatMulInteger
 * Name: n/a
 * Inputs: in0, in1, a_zero_point, b_zero_point
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_matmulinteger(const uint8_t input0[2][3], const uint8_t input1[3][4], const uint8_t input0_zero_point[1], const uint8_t input1_zero_point[1], int32_t output[2][4]) {
    const int32_t input0_zero = (int32_t)input0_zero_point[0];
    const int32_t input1_zero = (int32_t)input1_zero_point[0];
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 4; ++i1) {
            int32_t acc = 0;
            for (idx_t k = 0; k < 3; ++k) {
                acc += ((int32_t)input0[i0][k] - input0_zero) * ((int32_t)input1[k][i1] - input1_zero);
            }
            output[i0][i1] = (int32_t)acc;
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const uint8_t in0[restrict 2][3], int32_t out[restrict 2][4]) {
    node0_matmulinteger(in0, weight1_in1, weight2_a_zero_point, weight3_b_zero_point, out);
}
