/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 6e4975caa3f85c3d396a70c68fe69af9ec085174c6a524f3dd943c1f49e4b8f6
 * Model name: model
 * Graph name: multihead_attention_graph
 * Inputs: 4 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13, com.microsoft=1
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

static inline float ref_scalar_f32_maximum(float a, float b) {
    return fmaxf(a, b);
}

static inline float ref_scalar_f32_exp(float a) {
    return expf(a);
}

/*
 * Node 0:
 * OpType: MultiHeadAttention
 * Name: n/a
 * Inputs: query, key, value, bias, , , , 
 * Outputs: output
 * Attrs:
 *   num_heads: 2
 */
EMX_NODE_FN void node0_multiheadattention(const float query[1][2][8], const float key[1][3][8], const float value[1][3][8], const float bias[24], float output[1][2][8]) {
    const float scale = 0.5f;
    for (int b = 0; b < 1; ++b) {
        for (int h = 0; h < 2; ++h) {
            for (int qi = 0; qi < 2; ++qi) {
                float scores[3];
                float max_score = -INFINITY;
                for (int ki = 0; ki < 3; ++ki) {
                    float score = 0.0f;
                    for (int d = 0; d < 4; ++d) {
                        float q_val = query[b][qi][h * 4 + d] + bias[h * 4 + d];
                        float k_val = key[b][ki][h * 4 + d] + bias[8 + h * 4 + d];
                        score += q_val * k_val;
                    }
                    score *= scale;
                    scores[ki] = score;
                    max_score = ref_scalar_f32_maximum(max_score, score);
                }
                float sum = 0.0f;
                for (int ki = 0; ki < 3; ++ki) {
                    float w = 0.0f;
                    if (max_score != -INFINITY) {
                        w = ref_scalar_f32_exp(scores[ki] - max_score);
                    }
                    scores[ki] = w;
                    sum += w;
                }
                float inv_sum = sum == 0.0f ? 0.0f : (float)1 / sum;
                for (int vd = 0; vd < 4; ++vd) {
                    float acc = 0.0f;
                    for (int ki = 0; ki < 3; ++ki) {
                        float weight_val = scores[ki] * inv_sum;
                        {
                            float v_val = value[b][ki][h * 4 + vd] + bias[8 + 8 + h * 4 + vd];
                            acc += weight_val * v_val;
                        }
                    }
                    output[b][qi][h * 4 + vd] = acc;
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float query[restrict 1][2][8], const float key[restrict 1][3][8], const float value[restrict 1][3][8], const float bias[restrict 24], float output[restrict 1][2][8]) {
    node0_multiheadattention(query, key, value, bias, output);
}
