/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 6ea0a5ff0598acdd381227ff734e6d24aff9df4702b640b6716d1099086e6570
 * Model name: model
 * Graph name: ms_attention_graph
 * Inputs: 3 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13, com.microsoft=1
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

static inline float ref_scalar_f32_maximum(float a, float b) {
    return fmaxf(a, b);
}

static inline float ref_scalar_f32_exp(float a) {
    return expf(a);
}

/*
 * Node 0:
 * OpType: Attention
 * Name: n/a
 * Inputs: input, weight, bias
 * Outputs: output
 * Attrs:
 *   num_heads: 2
 */
EMX_NODE_FN void node0_attention(const float input0[1][2][4], const float weight[4][12], const float bias[12], float output[1][2][4]) {
    const float scale = 0.707106781f;
    for (int b = 0; b < 1; ++b) {
        for (int h = 0; h < 2; ++h) {
            for (int qi = 0; qi < 2; ++qi) {
                float q[2];
                for (int d = 0; d < 2; ++d) {
                    float q_val = 0.0f;
                    for (int j = 0; j < 4; ++j) {
                        q_val += input0[b][qi][j] * weight[j][h * 2 + d];
                    }
                    q[d] = q_val + bias[h * 2 + d];
                }
                float scores[2];
                float max_score = -INFINITY;
                for (int ki = 0; ki < 2; ++ki) {
                    float score = 0.0f;
                    for (int d = 0; d < 2; ++d) {
                        float k_val = 0.0f;
                        for (int j = 0; j < 4; ++j) {
                            k_val += input0[b][ki][j] * weight[j][4 + h * 2 + d];
                        }
                        k_val += bias[4 + h * 2 + d];
                        score += q[d] * k_val;
                    }
                    score *= scale;
                    scores[ki] = score;
                    max_score = ref_scalar_f32_maximum(max_score, score);
                }
                float sum = 0.0f;
                for (int ki = 0; ki < 2; ++ki) {
                    float w = 0.0f;
                    if (max_score != -INFINITY) {
                        w = ref_scalar_f32_exp(scores[ki] - max_score);
                    }
                    scores[ki] = w;
                    sum += w;
                }
                float inv_sum = sum == 0.0f ? 0.0f : (float)1 / sum;
                for (int vd = 0; vd < 2; ++vd) {
                    float acc = 0.0f;
                    for (int ki = 0; ki < 2; ++ki) {
                        float weight_val = scores[ki] * inv_sum;
                        {
                            float v_val = 0.0f;
                            for (int j = 0; j < 4; ++j) {
                                v_val += input0[b][ki][j] * weight[j][4 + 4 + h * 2 + vd];
                            }
                            v_val += bias[4 + 4 + h * 2 + vd];
                            acc += weight_val * v_val;
                        }
                    }
                    output[b][qi][h * 2 + vd] = acc;
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 1][2][4], const float weight[restrict 4][12], const float bias[restrict 12], float output[restrict 1][2][4]) {
    node0_attention(input, weight, bias, output);
}
