/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): c3da431744146761cac98d1cbc1b2ff52fbbefbc4b039d2b0e42689632617f2f
 * Model name: model
 * Graph name: optional_has_element_no_input_graph
 * Inputs: 0 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdbool.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: OptionalHasElement
 * Name: n/a
 * Inputs: n/a
 * Outputs: output
 * Attrs: n/a
 */
EMX_NODE_FN void node0_optionalhaselement(bool output[1]) {
    output[0] = 0;
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(bool output[restrict 1]) {
    node0_optionalhaselement(output);
}
