/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): da8e4c2b180abc6dfdfa9c44894bd510649be908d4e07bad79a1aaaac9446f2d
 * Model name: model
 * Graph name: optional_has_element_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdbool.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif

/*
 * Node 0:
 * OpType: OptionalHasElement
 * Name: n/a
 * Inputs: optional_input
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_optionalhaselement(const float input0[4], const _Bool optional_input_present, bool output[1]) {
    (void)input0;
    output[0] = optional_input_present;
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float optional_input[restrict 4], _Bool optional_input_present, bool output[restrict 1]) {
    node0_optionalhaselement(optional_input, optional_input_present, output);
}
