/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 7dccc1b72c4b3f41a6e3503087718180b1608365b9b5253af4bc4ef1d26528c5
 * Model name: model
 * Graph name: optional_get_element_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: OptionalGetElement
 * Name: n/a
 * Inputs: optional_input
 * Outputs: output
 * Attrs: n/a
 */
EMX_NODE_FN void node0_optionalgetelement(const float input0[4], float output[4]) {
    for (idx_t i0 = 0; i0 < 4; ++i0) {
        output[i0] = input0[i0];
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float optional_input[restrict 4], _Bool optional_input_present, float output[restrict 4]) {
    node0_optionalgetelement(optional_input, output);
}
