/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): e4620ccda6f8df29da3780f4293d6f9133eb776e6eae7a11f6ad2e8b3c3524b3
 * Model name: model
 * Graph name: optional_get_element_seq_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: OptionalGetElement
 * Name: n/a
 * Inputs: seq_input
 * Outputs: output
 * Attrs: n/a
 */
void node0_optionalgetelement(const float input_sequence[EMX_SEQUENCE_MAX_LEN][4], const idx_t input_sequence__count, float output_sequence[EMX_SEQUENCE_MAX_LEN][4], idx_t * output_sequence__count) {
    idx_t input_count = input_sequence__count;
    if (input_count > EMX_SEQUENCE_MAX_LEN) {
        input_count = EMX_SEQUENCE_MAX_LEN;
    }

    for (idx_t seq = 0; seq < input_count; ++seq) {
        for (idx_t elem = 0; elem < 4; ++elem) {
            ((float *)output_sequence[seq])[elem] = ((const float *)input_sequence[seq])[elem];
        }
    }

    *output_sequence__count = input_count;
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float seq_input[EMX_SEQUENCE_MAX_LEN][4], idx_t seq_input__count, float output[EMX_SEQUENCE_MAX_LEN][4], idx_t *output__count) {
    node0_optionalgetelement(seq_input, seq_input__count, output, output__count);
}
