/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   template_dir: package default
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: fp64
 *   fp16_accumulation_strategy: fp32
 *   truncate_weights_after: n/a
 *   large_temp_threshold_bytes: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 078ebc9deff678318d17c10fd0e61ced036560c84139a38f8de6b108e7d8edf3
 * Model name: model
 * Graph name: optional_has_element_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdbool.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif

/*
 * Node 0:
 * OpType: OptionalHasElement
 * Name: n/a
 * Inputs: optional_input
 * Outputs: output
 * Attrs: n/a
 */
static inline void node0_optionalhaselement(const float input0[4], const _Bool optional_input_present, bool output[1]) {
    (void)input0;
    output[0] = optional_input_present;
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float optional_input[restrict 4], _Bool optional_input_present, bool output[restrict 1]) {
    node0_optionalhaselement(optional_input, optional_input_present, output);
}
