/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 8e2945898e1fa607b14473bd807e53f2659db0528a0247320105125ef434b99b
 * Model name: model
 * Graph name: pad_dynamic_axes_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=18
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stddef.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const int64_t weight1_pads[4];

/*
 * Weight 1:
 * Name: weight1_pads
 * Shape: (4,)
 * Elements: 4
 * Dtype: int64
 */
const EMX_UNUSED int64_t weight1_pads[4] = {
    0LL, 1LL, 0LL, 1LL
};

/*
 * Node 0:
 * OpType: Pad
 * Name: n/a
 * Inputs: input, pads, , axes
 * Outputs: output
 * Attrs:
 *   mode: constant
 */
EMX_NODE_FN void node0_pad(const float input[2][3], const int64_t axes[2], float output[2][5]) {
    const float *input_flat = (const float *)input;
    const int64_t pad_values[] = { 0, 1, 0, 1 };
    idx_t pad_begin[2];
    for (idx_t pad_index = 0; pad_index < 2; ++pad_index) {
        pad_begin[pad_index] = 0;
    }
    for (idx_t axis_index = 0; axis_index < 2; ++axis_index) {
        int axis = (int)axes[axis_index];
        if (axis < 0) {
            axis += 2;
        }
        if (axis < 0 || axis >= 2) {
            return;
        }
        pad_begin[axis] = pad_values[axis_index];
    }
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 5; ++i1) {
            output[i0][i1] = 0.0f;
        }
    }
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 5; ++i1) {
            idx_t pad_index = 0;
            int pad_in_bounds = 1;
            idx_t pad_idx0 = i0 - (idx_t)(pad_begin[0]);
            if (2 == 0) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds && (pad_idx0 < 0 || pad_idx0 >= 2)) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds) {
                pad_index += pad_idx0 * 3;
            }
            idx_t pad_idx1 = i1 - (idx_t)(pad_begin[1]);
            if (3 == 0) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds && (pad_idx1 < 0 || pad_idx1 >= 3)) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds) {
                pad_index += pad_idx1 * 1;
            }
            if (!pad_in_bounds) {
            } else {
                output[i0][i1] = input_flat[pad_index];
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 2][3], const int64_t axes[restrict 2], float output[restrict 2][5]) {
    node0_pad(input, axes, output);
}
