/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 01d42bff2a59f2dbaaeb53cdd1cf1c03d39dc8d60272645cfcb2b1c185250285
 * Model name: model
 * Graph name: pad_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 2
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stddef.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

extern const int64_t weight1_pads[4];
extern const float weight2_value[1];

/*
 * Weight 1:
 * Name: weight1_pads
 * Shape: (4,)
 * Elements: 4
 * Dtype: int64
 */
const EMX_UNUSED int64_t weight1_pads[4] = {
    0LL, 1LL, 0LL, 1LL
};

/*
 * Weight 2:
 * Name: weight2_value
 * Shape: []
 * Elements: 1
 * Dtype: float
 */
const EMX_UNUSED float weight2_value[1] = {
    0x0.0p+0f
};

/*
 * Node 0:
 * OpType: Pad
 * Name: n/a
 * Inputs: input, pads, value
 * Outputs: output
 * Attrs:
 *   mode: constant
 */
EMX_NODE_FN void node0_pad(const float input[2][3], float output[2][5]) {
    const float *input_flat = (const float *)input;
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 5; ++i1) {
            output[i0][i1] = 0.0f;
        }
    }
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 5; ++i1) {
            idx_t pad_index = 0;
            int pad_in_bounds = 1;
            idx_t pad_idx0 = i0 - (idx_t)(0);
            if (2 == 0) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds && (pad_idx0 < 0 || pad_idx0 >= 2)) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds) {
                pad_index += pad_idx0 * 3;
            }
            idx_t pad_idx1 = i1 - (idx_t)(1);
            if (3 == 0) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds && (pad_idx1 < 0 || pad_idx1 >= 3)) {
                pad_in_bounds = 0;
            }
            if (pad_in_bounds) {
                pad_index += pad_idx1 * 1;
            }
            if (!pad_in_bounds) {
            } else {
                output[i0][i1] = input_flat[pad_index];
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float input[restrict 2][3], float output[restrict 2][5]) {
    node0_pad(input, output);
}
