/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 6a7bdce37f626466fec331cee190821a24aefb98797fbc9fd6b589be686c8ff8
 * Model name: model
 * Graph name: rnn_graph
 * Inputs: 3 Outputs: 2 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=14
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>
#include <float.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

static inline float ref_scalar_f32_tanh(float a) {
    return tanhf(a);
}

/*
 * Node 0:
 * OpType: RNN
 * Name: n/a
 * Inputs: X, W, R
 * Outputs: Y, Y_h
 * Attrs:
 *   hidden_size: 3
 *   layout: 0
 */
EMX_NODE_FN void node0_rnn(const float input_x[1][1][2], const float input_w[1][3][2], const float input_r[1][3][3], float output_y[1][1][1][3], float output_y_h[1][1][3]) {
    {
        const int dir = 0;
        const int reverse = 0;
        float H_prev[1][3];
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                H_prev[b][h] = 0.0f;
            }
        }
        for (int b = 0; b < 1; ++b) {
            int seq_limit = 1;
            for (int step = 0; step < seq_limit; ++step) {
                int t = reverse ? (seq_limit - 1 - step) : step;
                float H_next[3];
                for (int h = 0; h < 3; ++h) {
                    float sum = 0.0f;
                    for (int i = 0; i < 2; ++i) {
                        float x_val = input_x[t][b][i];
                        sum += x_val * input_w[dir][h][i];
                    }
                    for (int i = 0; i < 3; ++i) {
                        sum += H_prev[b][i] * input_r[dir][h][i];
                    }
                    float h_new = ref_scalar_f32_tanh(sum);
                    H_next[h] = h_new;
                    output_y[step][dir][b][h] = h_new;
                }
                for (int h = 0; h < 3; ++h) {
                    H_prev[b][h] = H_next[h];
                }
            }
            for (int step = seq_limit; step < 1; ++step) {
                for (int h = 0; h < 3; ++h) {
                    output_y[step][dir][b][h] = 0.0f;
                }
            }
        }
        for (int b = 0; b < 1; ++b) {
            for (int h = 0; h < 3; ++h) {
                output_y_h[dir][b][h] = H_prev[b][h];
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float X[restrict 1][1][2], const float W[restrict 1][3][2], const float R[restrict 1][3][3], float Y[restrict 1][1][1][3], float Y_h[restrict 1][1][3]) {
    node0_rnn(X, W, R, Y, Y_h);
}
