/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 0a4fb61e2adb7110805e16c915670537c6ee2c4d5688af2f43852015b71c3d8f
 * Model name: model
 * Graph name: regex_full_match_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 9
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=20
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: RegexFullMatch
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   pattern: ab
 */
static const uint8_t node0_regexfullmatch_regex_transitions[4][256] = {
    /* state 0 */ { 0 },
    /* state 1 */ { ['a'] = 2 },
    /* state 2 */ { ['b'] = 3 },
    /* state 3 */ { 0 },
};

/* regex:                "ab"
* flags:                ""
* encoding:             utf8
* alphabet-compression: no
* row-deduplication:    no
* early-exit:           no
*/
static inline bool node0_regexfullmatch_regex_match(const char *input, size_t len) {
    uint8_t state = 1;
    for (size_t i = 0; i < len; i++) {
        state = node0_regexfullmatch_regex_transitions[state][(unsigned char)input[i]];
    }
    return state >= 3;
}

EMX_NODE_FN void node0_regexfullmatch(const char input0[2][EMX_STRING_MAX_LEN], bool output[2]) {
    const char (*input_flat)[EMX_STRING_MAX_LEN] = (const char (*)[EMX_STRING_MAX_LEN])input0;
    bool *output_flat = (bool *)output;
    for (idx_t i = 0; i < 2; ++i) {
        output_flat[i] = node0_regexfullmatch_regex_match(input_flat[i], strlen(input_flat[i]));
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const char in0[restrict 2][EMX_STRING_MAX_LEN], bool out[restrict 2]) {
    node0_regexfullmatch(in0, out);
}
