/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): d923c995c27ee80162f156129b2c7996139d9b8a3a9e7b6f80bbc615c19eb58e
 * Model name: model
 * Graph name: scatter_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 1
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=10
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif

extern const int64_t weight1_indices[2][3];

/*
 * Weight 1:
 * Name: weight1_indices
 * Shape: (2, 3)
 * Elements: 6
 * Dtype: int64
 */
const EMX_UNUSED int64_t weight1_indices[2][3] = {
    {
        0LL, 1LL, 2LL
    },
    {
        0LL, 1LL, 2LL
    }
};

/*
 * Node 0:
 * OpType: Scatter
 * Name: n/a
 * Inputs: data, indices, updates
 * Outputs: output
 * Attrs:
 *   axis: 1
 */
static inline void node0_scatter(const float data[2][3], const int64_t indices[2][3], const float updates[2][3], float output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = data[i0][i1];
        }
    }

    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            idx_t scatter_index = indices[i0][i1];
            if (scatter_index < 0) {
                scatter_index += 3;
            }
            output[i0][scatter_index] = updates[i0][i1];
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float data[restrict 2][3], const float updates[restrict 2][3], float output[restrict 2][3]) {
    node0_scatter(data, weight1_indices, updates, output);
}
