/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 9f2394718ce05cf614d064eeb6e1e970492240f3cb46f51c1d721609af12efcd
 * Model name: model
 * Graph name: transpose_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: onnx2c (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: Transpose
 * Name: n/a
 * Inputs: in0
 * Outputs: out
 * Attrs:
 *   perm: [2, 0, 1]
 */
static inline void node0_transpose(const float input0[2][3][4], float output[4][2][3]) {
    for (idx_t i0 = 0; i0 < 4; ++i0) {
        for (idx_t i1 = 0; i1 < 2; ++i1) {
            for (idx_t i2 = 0; i2 < 3; ++i2) {
                output[i0][i1][i2] = input0[i1][i2][i0];
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float in0[restrict 2][3][4], float out[restrict 4][2][3]) {
    node0_transpose(in0, out);
}
