/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 7f30a57eebb5c9ae99b2a7e26899f206f8d9d623a8e0a2518c4f271128c51d8c
 * Model name: model
 * Graph name: where_graph
 * Inputs: 3 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdbool.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif

/*
 * Node 0:
 * OpType: Where
 * Name: n/a
 * Inputs: condition, x, y
 * Outputs: out
 * Attrs: n/a
 */
static inline void node0_where(const bool condition[2][3], const float input_x[2][3], const float input_y[2][3], float output[2][3]) {
    for (idx_t i0 = 0; i0 < 2; ++i0) {
        for (idx_t i1 = 0; i1 < 3; ++i1) {
            output[i0][i1] = condition[i0][i1] ? input_x[i0][i1] : input_y[i0][i1];
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const bool condition[restrict 2][3], const float x[restrict 2][3], const float y[restrict 2][3], float out[restrict 2][3]) {
    node0_where(condition, x, y, out);
}
