/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 172892217c3338264daaea2b88a264f20cf52c729aeaef90111106fe758dec0c
 * Model name: ragged_sequence_identity_model
 * Graph name: ragged_sequence_identity_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: Identity
 * Name: n/a
 * Inputs: seq_in
 * Outputs: seq_out
 * Attrs: n/a
 */
void node0_identity(const float input_sequence[EMX_SEQUENCE_MAX_LEN][8], const idx_t input_sequence__count, float output_sequence[EMX_SEQUENCE_MAX_LEN][8], idx_t * output_sequence__count, const idx_t input_sequence_dim_0[EMX_SEQUENCE_MAX_LEN], idx_t output_sequence_dim_0[EMX_SEQUENCE_MAX_LEN]) {
    idx_t input_count = input_sequence__count;
    if (input_count > EMX_SEQUENCE_MAX_LEN) {
        input_count = EMX_SEQUENCE_MAX_LEN;
    }

    for (idx_t seq = 0; seq < input_count; ++seq) {
        output_sequence_dim_0[seq] =
        input_sequence_dim_0[seq];
        for (idx_t elem = 0; elem < 8; ++elem) {
            ((float *)output_sequence[seq])[elem] = ((const float *)input_sequence[seq])[elem];
        }
    }

    *output_sequence__count = input_count;
}

_Bool ragged_sequence_identity_model_load(const char *path) {
    (void)path;
    return 1;
}

void ragged_sequence_identity_model(const float seq_in[EMX_SEQUENCE_MAX_LEN][8], idx_t seq_in__count, const idx_t seq_in__dim_0[EMX_SEQUENCE_MAX_LEN], float seq_out[EMX_SEQUENCE_MAX_LEN][8], idx_t *seq_out__count, idx_t seq_out__dim_0[EMX_SEQUENCE_MAX_LEN]) {
    node0_identity(seq_in, seq_in__count, seq_out, seq_out__count, seq_in__dim_0, seq_out__dim_0);
}
