/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 813c8d335bf58df5d7ef8561811d35a191a7df76504a91dc30c0c7cfbf43a3ee
 * Model name: sequence_io_model
 * Graph name: sequence_io_graph
 * Inputs: 2 Outputs: 2 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=13
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: Identity
 * Name: n/a
 * Inputs: x
 * Outputs: y
 * Attrs: n/a
 */
EMX_NODE_FN void node0_identity(const float input0[1], float output[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        output[i0] = input0[i0];
    }
}

_Bool sequence_io_model_load(const char *path) {
    (void)path;
    return 1;
}

void sequence_io_model(const float seq_in[EMX_SEQUENCE_MAX_LEN][2][3], idx_t seq_in__count, const float x[restrict 1], float seq_out[EMX_SEQUENCE_MAX_LEN][2][3], idx_t *seq_out__count, float y[restrict 1]) {
    node0_identity(x, y);
}
