/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): 142b60187b83941fbf6e60ac2793a85973694982d5c8174b353ae5271ccccc1f
 * Model name: string_concat_model
 * Graph name: string_concat_graph
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 9
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=20
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <string.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: StringConcat
 * Name: n/a
 * Inputs: x, y
 * Outputs: out
 * Attrs: n/a
 */
EMX_NODE_FN void node0_stringconcat(const char input0[3][EMX_STRING_MAX_LEN], const char input1[1][EMX_STRING_MAX_LEN], char output[3][EMX_STRING_MAX_LEN]) {
    for (idx_t i0 = 0; i0 < 3; ++i0) {
        const char *src0 = input0[i0];
        const char *src1 = input1[0];
        char *dst = output[i0];
        strncpy(dst, src0, EMX_STRING_MAX_LEN - 1);
        dst[EMX_STRING_MAX_LEN - 1] = '\0';
        strncat(dst, src1, EMX_STRING_MAX_LEN - 1 - strlen(dst));
    }
}

_Bool string_concat_model_load(const char *path) {
    (void)path;
    return 1;
}

void string_concat_model(const char x[restrict 3][EMX_STRING_MAX_LEN], const char y[restrict 1][EMX_STRING_MAX_LEN], char out[restrict 3][EMX_STRING_MAX_LEN]) {
    node0_stringconcat(x, y, out);
}
