/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): b162788f5ad09e9721bf5fee92232dd3d011da5b9944dcfb92cae4b0598d4b14
 * Model name: string_normalizer_model
 * Graph name: string_normalizer_graph
 * Inputs: 1 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 7
 * Model version: n/a
 * Domain: n/a
 * Producer: emx-onnx-cgen (version: n/a)
 * Opset imports: ai.onnx=10
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <ctype.h>
#include <string.h>
#include <strings.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif

/*
 * Node 0:
 * OpType: StringNormalizer
 * Name: n/a
 * Inputs: x
 * Outputs: out
 * Attrs:
 *   case_change_action: UPPER
 *   is_case_sensitive: 1
 *   stopwords: [monday]
 */
static inline void node0_stringnormalizer(const char input0[4][EMX_STRING_MAX_LEN], char output[3][EMX_STRING_MAX_LEN]) {
    idx_t out_idx = 0;
    for (idx_t in_idx = 0; in_idx < 4; ++in_idx) {
        const char *src = input0[in_idx];
        _Bool keep = true;
        if (strcmp(src, "monday") == 0) keep = false;
        if (!keep) {
            continue;
        }
        char *dst = output[out_idx++];
        size_t pos = 0;
        for (size_t i = 0; src[i] != '\0' && pos + 1 < EMX_STRING_MAX_LEN; ++i) {
            unsigned char ch = (unsigned char)src[i];
            ch = (unsigned char)toupper((int)ch);
            dst[pos++] = (char)ch;
        }
        dst[pos] = '\0';
    }
    for (; out_idx < 3; ++out_idx) {
        output[out_idx][0] = '\0';
    }
}

_Bool string_normalizer_model_load(const char *path) {
    (void)path;
    return 1;
}

void string_normalizer_model(const char x[restrict 4][EMX_STRING_MAX_LEN], char out[restrict 3][EMX_STRING_MAX_LEN]) {
    node0_stringnormalizer(x, out);
}
