from __future__ import annotations

import importlib

from .registry import get_lowering, register_lowering

_LOWERING_MODULES = [
    "adam",
    "adagrad",
    "affine_grid",
    "momentum",
    "arg_reduce",
    "array_feature_extractor",
    "attention",
    "average_pool",
    "batch_normalization",
    "bernoulli",
    "blackman_window",
    "cast",
    "center_crop_pad",
    "col2im",
    "compress",
    "concat",
    "concat_from_sequence",
    "constant_of_shape",
    "conv",
    "conv_integer",
    "conv_transpose",
    "deform_conv",
    "det",
    "cumsum",
    "depth_space",
    "dequantize_linear",
    "dynamic_quantize_linear",
    "dropout",
    "dft",
    "einsum",
    "elementwise",
    "expand",
    "eye_like",
    "flatten",
    "gather",
    "gather_elements",
    "gather_nd",
    "gemm",
    "global_max_pool",
    "grid_sample",
    "gru",
    "group_normalization",
    "hardmax",
    "hamming_window",
    "hann_window",
    "identity",
    "if_op",
    "instance_normalization",
    "label_encoder",
    "layer_normalization",
    "logsoftmax",
    "loop",
    "lp_normalization",
    "lp_pool",
    "lrn",
    "lstm",
    "matmul",
    "matmul_integer",
    "matmul_nbits",
    "maxpool",
    "maxunpool",
    "mean_variance_normalization",
    "mel_weight_matrix",
    "negative_log_likelihood_loss",
    "non_max_suppression",
    "nonzero",
    "optional_get_element",
    "optional_has_element",
    "one_hot",
    "pad",
    "qlinear_conv",
    "qlinear_add",
    "qlinear_matmul",
    "qlinear_mul",
    "qlinear_softmax",
    "quantize_linear",
    "random_uniform",
    "random_uniform_like",
    "regex_full_match",
    "range",
    "reduce",
    "reshape",
    "resize",
    "reverse_sequence",
    "rnn",
    "sequence_at",
    "sequence_construct",
    "sequence_empty",
    "sequence_erase",
    "sequence_insert",
    "sequence_length",
    "rms_normalization",
    "rotary_embedding",
    "roi_align",
    "scatter",
    "scatter_elements",
    "scatter_nd",
    "shape",
    "size",
    "slice",
    "softmax",
    "softmax_cross_entropy_loss",
    "split",
    "split_to_sequence",
    "string_concat",
    "string_normalizer",
    "string_split",
    "stft",
    "squeeze",
    "tensor_scatter",
    "tfidf_vectorizer",
    "tile",
    "tree_ensemble",
    "tree_ensemble_classifier",
    "topk",
    "transpose",
    "unique",
    "trilu",
    "unsqueeze",
    "upsample",
    "variadic",
    "where",
]


def load_lowering_registry() -> None:
    for module_name in _LOWERING_MODULES:
        importlib.import_module(f"{__name__}.{module_name}")


__all__ = ["get_lowering", "register_lowering", "load_lowering_registry"]
