from __future__ import annotations

import importlib

from .registry import get_lowering, register_lowering

_LOWERING_MODULES = [
    "adagrad",
    "arg_reduce",
    "attention",
    "average_pool",
    "batch_normalization",
    "bernoulli",
    "cast",
    "compress",
    "concat",
    "constant_of_shape",
    "conv",
    "conv_integer",
    "conv_transpose",
    "cumsum",
    "depth_space",
    "dequantize_linear",
    "dropout",
    "einsum",
    "elementwise",
    "expand",
    "eye_like",
    "flatten",
    "gather",
    "gather_elements",
    "gather_nd",
    "gemm",
    "global_max_pool",
    "grid_sample",
    "gru",
    "group_normalization",
    "hardmax",
    "hamming_window",
    "identity",
    "instance_normalization",
    "layer_normalization",
    "logsoftmax",
    "lp_normalization",
    "lp_pool",
    "lrn",
    "lstm",
    "matmul",
    "matmul_integer",
    "maxpool",
    "mean_variance_normalization",
    "negative_log_likelihood_loss",
    "non_max_suppression",
    "nonzero",
    "optional_has_element",
    "one_hot",
    "pad",
    "qlinear_conv",
    "qlinear_matmul",
    "qlinear_mul",
    "quantize_linear",
    "range",
    "reduce",
    "reshape",
    "resize",
    "reverse_sequence",
    "rms_normalization",
    "rotary_embedding",
    "scatter",
    "scatter_nd",
    "shape",
    "size",
    "slice",
    "softmax",
    "softmax_cross_entropy_loss",
    "split",
    "string_normalizer",
    "squeeze",
    "tensor_scatter",
    "tfidf_vectorizer",
    "tile",
    "topk",
    "transpose",
    "unique",
    "trilu",
    "unsqueeze",
    "upsample",
    "variadic",
    "where",
]


def load_lowering_registry() -> None:
    for module_name in _LOWERING_MODULES:
        importlib.import_module(f"{__name__}.{module_name}")


__all__ = ["get_lowering", "register_lowering", "load_lowering_registry"]
