/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: False
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): bef4c6d7ee705cefa17c64523089b525b3bae6ed9296033f84e7e0a5c8816c2e
 * Model name: model
 * Graph name: test_affine_grid_3d
 * Inputs: 2 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 9
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=20
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <math.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: AffineGrid
 * Name: n/a
 * Inputs: theta, size
 * Outputs: grid
 * Attrs:
 *   align_corners: 0
 */
EMX_NODE_FN void node0_affinegrid(const float theta[2][3][4], const int64_t size[5], float grid[2][4][5][6][3]) {
    for (idx_t n = 0; n < 2; ++n) {
        for (idx_t d = 0; d < 4; ++d) {
            for (idx_t h = 0; h < 5; ++h) {
                for (idx_t w = 0; w < 6; ++w) {
                    const float z_coord = (float)-1 + ((float)2 * d + (float)1) / (float)4;
                    const float y_coord = (float)-1 + ((float)2 * h + (float)1) / (float)5;
                    const float x_coord = (float)-1 + ((float)2 * w + (float)1) / (float)6;
                    grid[n][d][h][w][0] = theta[n][0][0] * x_coord + theta[n][0][1] * y_coord + theta[n][0][2] * z_coord + theta[n][0][3];
                    grid[n][d][h][w][1] = theta[n][1][0] * x_coord + theta[n][1][1] * y_coord + theta[n][1][2] * z_coord + theta[n][1][3];
                    grid[n][d][h][w][2] = theta[n][2][0] * x_coord + theta[n][2][1] * y_coord + theta[n][2][2] * z_coord + theta[n][2][3];
                }
            }
        }
    }
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const float theta[restrict 2][3][4], const int64_t size[restrict 5], float grid[restrict 2][4][5][6][3]) {
    node0_affinegrid(theta, size, grid);
}
