/*
 * Generated by emmtrix ONNX-to-C Code Generator (emx-onnx-cgen)
 *
 * Codegen settings:
 *   emit_testbench: True
 *   restrict_arrays: True
 *   fp32_accumulation_strategy: simple
 *   fp16_accumulation_strategy: fp32
 *   large_temp_threshold: 1024
 *   large_weight_threshold: 102400
 * Model checksum (sha256): a88d26410c916cafe8e9791fd29fd25fe4ec7483027e6f12224b447c82703601
 * Model name: model
 * Graph name: test_loop16_seq_none
 * Inputs: 3 Outputs: 1 Nodes: 1 Initializers: 0
 * IR version: 8
 * Model version: n/a
 * Domain: n/a
 * Producer: backend-test (version: n/a)
 * Opset imports: ai.onnx=16
 * Description:
 *   n/a
 * Graph description:
 *   n/a
 * Metadata:
 *   n/a
 */

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>

#ifndef idx_t
#define idx_t int32_t
#endif
#ifndef EMX_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define EMX_UNUSED __attribute__((unused))
#else
#define EMX_UNUSED
#endif
#endif
#ifndef EMX_NODE_FN
#define EMX_NODE_FN static inline
#endif
#ifndef EMX_STRING_MAX_LEN
#define EMX_STRING_MAX_LEN 256
#endif
#ifndef EMX_SEQUENCE_MAX_LEN
#define EMX_SEQUENCE_MAX_LEN 32
#endif

/*
 * Node 0:
 * OpType: Loop
 * Name: n/a
 * Inputs: trip_count, cond, opt_seq
 * Outputs: seq_res
 * Attrs:
 *   body: GraphProto('loop_body', input=<3 inputs>, output=<2 outputs>, node=<12 nodes>, value_info=<10 value_info>)
 */
void node0_loop(const int64_t trip_count[1], const bool cond[1], const float input_sequence[EMX_SEQUENCE_MAX_LEN][1], const idx_t input_sequence__count, const _Bool input_sequence_present, float output_sequence[EMX_SEQUENCE_MAX_LEN][1], idx_t * output_sequence__count) {
    idx_t input_count;
    if (input_sequence_present) {
        input_count = input_sequence__count;
        if (input_count > EMX_SEQUENCE_MAX_LEN) {
            input_count = EMX_SEQUENCE_MAX_LEN;
        }
        for (idx_t seq = 0; seq < input_count; ++seq) {
            for (idx_t elem = 0; elem < 1; ++elem) {
                output_sequence[seq][elem] = input_sequence[seq][elem];
            }
        }
    } else {
        input_count = 1;
        for (idx_t elem = 0; elem < 1; ++elem) {
            output_sequence[0][elem] = 0.0f;
        }
    }

    const int64_t trip_raw = (int64_t)trip_count[0];
    const bool enabled = cond[0];
    if (!enabled || trip_raw <= 0) {
        *output_sequence__count = input_count;
        return;
    }

    const int64_t limit_by_trip = trip_raw;
    const int64_t limit_by_table = 5;
    const int64_t limit_by_capacity = (int64_t)EMX_SEQUENCE_MAX_LEN - (int64_t)input_count;
    int64_t append_count = limit_by_trip;
    if (append_count > limit_by_table) {
        append_count = limit_by_table;
    }
    if (append_count > limit_by_capacity) {
        append_count = limit_by_capacity;
    }
    if (append_count < 0) {
        append_count = 0;
    }

    static const float loop_insert_table[5] = { 1.0f, 1.0f, 1.0f, 1.0f, 1.0f };
    for (int64_t idx = 0; idx < append_count; ++idx) {
        output_sequence[input_count + (idx_t)idx][0] = loop_insert_table[idx];
    }
    *output_sequence__count = input_count + (idx_t)append_count;
}

_Bool model_load(const char *path) {
    (void)path;
    return 1;
}

void model(const int64_t trip_count[restrict 1], const bool cond[restrict 1], const float opt_seq[EMX_SEQUENCE_MAX_LEN][1], idx_t opt_seq__count, _Bool opt_seq_present, float seq_res[EMX_SEQUENCE_MAX_LEN][1], idx_t *seq_res__count) {
    node0_loop(trip_count, cond, opt_seq, opt_seq__count, opt_seq_present, seq_res, seq_res__count);
}

static uint64_t rng_state = 0x243f6a8885a308d3ull;

static uint64_t rng_next_u64(void) {
    uint64_t x = rng_state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    rng_state = x;
    return x * 0x2545f4914f6cdd1dull;
}

static float rng_next_float(void) {
    return (float)((double)rng_next_u64() * (1.0 / 18446744073709551616.0));
}



static const int64_t trip_count_testbench_data[] = {
    5LL
};
static const bool cond_testbench_data[] = {
    true
};

__attribute__((weak, noinline)) void timer_start(void) {}
__attribute__((weak, noinline)) void timer_stop(void) {}


static void testbench_init_constant_input(int64_t trip_count[1], bool cond[1]) {
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        trip_count[i0] = trip_count_testbench_data[i0];
    }
    for (idx_t i0 = 0; i0 < 1; ++i0) {
        cond[i0] = cond_testbench_data[i0];
    }
}

static int testbench_read_input_file(
const char *input_path, float opt_seq[EMX_SEQUENCE_MAX_LEN][1], idx_t *opt_seq__count, _Bool *opt_seq_present) {
    FILE *input_file = fopen(input_path, "rb");
    if (!input_file) {
        fprintf(stderr, "Failed to open input file: %s\n", input_path);
        return 1;
    }
    {
        uint8_t present = 1u;
        if (fread(&present, sizeof(uint8_t), 1, input_file) != 1) {
            fprintf(stderr, "Failed to read optional presence for input opt_seq\n");
            fclose(input_file);
            return 1;
        }
        *opt_seq_present = (present != 0u);
    }
    {
        int32_t sequence_count = 0;
        if (fread(&sequence_count, sizeof(int32_t), 1, input_file) != 1) {
            fprintf(stderr, "Failed to read sequence count for input opt_seq\n");
            fclose(input_file);
            return 1;
        }
        if (sequence_count < 0 || sequence_count > EMX_SEQUENCE_MAX_LEN) {
            fprintf(stderr, "Invalid sequence count for input opt_seq: %d\n", (int)sequence_count);
            fclose(input_file);
            return 1;
        }
        *opt_seq__count = (idx_t)sequence_count;
    }
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            if (fread(&opt_seq[i0][i1], sizeof(float), 1, input_file) != 1) {
                fprintf(stderr, "Failed to read input opt_seq\n");
                fclose(input_file);
                return 1;
            }
        }
    }

    fclose(input_file);
    return 0;
}

static void testbench_fill_random_input(float opt_seq[EMX_SEQUENCE_MAX_LEN][1], idx_t opt_seq__count) {
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            opt_seq[i0][i1] = rng_next_float();
        }
    }
}

static void testbench_print_json(
float seq_res[EMX_SEQUENCE_MAX_LEN][1], idx_t seq_res__count) {
    printf("{\n  \"outputs\": {\n");
    printf("    \"seq_res\": {\"shape\": [1], \"sequence_count\": %d, \"item_shapes\": [", (int)seq_res__count);
    for (idx_t seq = 0; seq < seq_res__count; ++seq) {
        if (seq) {
            printf(",");
        }
        printf("[");
        if (0) {
            printf(",");
        }
        printf("%d", 1);
        printf("]");
    }
    printf("], \"data\":\n      ");
    printf("[");
    for (idx_t i0 = 0; i0 < 32; ++i0) {
        if (i0) {
            printf(",\n      ");
        }
        printf("[");
        for (idx_t i1 = 0; i1 < 1; ++i1) {
            if (i1) {
                printf(",");
            }
            printf("\"%a\"", (double)seq_res[i0][i1]);
        }
        printf("]");
    }
    printf("]}");
    printf("\n  }\n}\n");
}

static int testbench_run(const char *input_path) {

    int64_t trip_count[1];
    bool cond[1];
    _Bool opt_seq_present = 1;
    float opt_seq[EMX_SEQUENCE_MAX_LEN][1];
    idx_t opt_seq__count = 32;

    testbench_init_constant_input(trip_count, cond);
    if (input_path) {
        if (testbench_read_input_file(input_path, opt_seq, &opt_seq__count, &opt_seq_present) != 0) {
            return 1;
        }
    } else {
        testbench_fill_random_input(opt_seq, opt_seq__count);
    }

    float seq_res[EMX_SEQUENCE_MAX_LEN][1];
    idx_t seq_res__count = 0;

    if (!model_load("model.bin")) {
        return 1;
    }

    timer_start();
    model(trip_count, cond, opt_seq, opt_seq__count, opt_seq_present, seq_res, &seq_res__count);
    timer_stop();

    testbench_print_json(seq_res, seq_res__count);
    return 0;
}

int main(int argc, char **argv) {
    const char *input_path = NULL;

    if (argc > 1) {
        input_path = argv[1];
    }

    return testbench_run(input_path);
}
